Change default connection pool idle timeout from 0 to null
micronaut-projects/micronaut-core pull request #10013
Opened 2023-10-23 15:37 UTC by yawkat

This was an oversight, but I think 0 should be handled the same way so not sure this PR changes anything in practice.

2023-10-23 16:01 UTC, graemerocher approved these changes

2023-10-23 19:21 UTC, sdelamo requested changes
Can you add a test which verifies the default value?

2023-10-24 07:48 UTC, dstepanov approved these changes

2023-10-24 08:13 UTC, graemerocher requested changes
Add a test

2023-10-24 08:20 UTC, yawkat commented
you want me to test that a field is null?

2023-10-24 09:55 UTC, graemerocher approved these changes

2023-10-24 09:55 UTC, merged