Tck: Tests for error handlers with flux controller methods
micronaut-projects/micronaut-core pull request #10025
Opened 2023-10-25 21:49 UTC by jeremyg484

- Handle and log HTTP/2 GOAWAY frame (#10007)
- Add eq/hc for HttpVersionSelection (#9999)
- Change default connection pool idle timeout from 0 to null (#10013)
- Allow onComplete before request in PipeliningServerHandler (#10017)
- fix: do not try to dispatch inside the event loop if channel is inactive (#10018)
- Tck: Test error handling with Flux controller methods

2023-10-26 09:59 UTC, sdelamo commented
@jeremyg484 did you forget to push the code?

2023-10-26 11:04 UTC, jeremyg484 commented
> @jeremyg484 did you forget to push the code?

@sdelamo Fixed.

2023-10-26 15:29 UTC, sdelamo requested changes

2023-10-26 15:29 UTC, sdelamo commented on http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/ErrorHandlerFluxTest.java
> +            return HttpResponse.<String>status(HttpStatus.BAD_REQUEST, "Bad request")
Respond a weird status code .e.g I am a teapot so we know in the test assertion we are being handled by the test error handler.

2023-10-26 15:31 UTC, sdelamo reviewed
The current assertions describe the current behavior, do they match your expected behavior? If not write comments in the test describing why they are not behaving as expected.

2023-10-26 18:16 UTC, jeremyg484 commented
In discussion with @yawkat, it was confirmed that my assumptions in questions #1 and #3 are correct and the existing behavior is as intended. Re: question #2, he also confirmed that it might be possible, but difficult, to change the implementation such that the error handler still gets invoked in the chunked response case if the error is signaled immediately before any data. 

I think it would be good to do this if we can, as it would be more consistent with the behavior of immediately thrown exceptions and less surprising to the user. @sdelamo I have added a comment to the `testErrorHandlerWithFluxChunkedSignaledImmediateError` method to point out this desired change. I will investigate the implementation further to see how it might be done.

The test has also been updated to have the error handler produce a more unusual status code (418) to better ensure the assertions are correctly identifying that the handler was invoked.

2023-10-27 04:56 UTC, sdelamo approved these changes

2023-10-27 04:56 UTC, merged