Document it is possible to use Java Records for immutable configuration with @ConfigurationProperties
micronaut-projects/micronaut-core pull request #10096
Opened 2023-11-09 19:27 UTC by wetted

closes #10086

2023-11-10 08:17 UTC, sdelamo requested changes

2023-11-10 08:17 UTC, sdelamo commented on src/main/docs/guide/config/immutableConfig.adoc
> +import io.micronaut.context.annotation.ConfigurationProperties;
this should be in code not in asciidoctor and we should have a test for the code shown in the documentation.

2023-11-10 17:10 UTC, wetted commented
@Sergio I am unable to get the generated HTML to render the Java Record snippet for some reason. Investigating...

2023-11-10 17:28 UTC, sdelamo approved these changes

2023-11-10 17:34 UTC, timyates commented
@wetted running `./gradlew docs -x htmlSanityCheck` locally, I see

<img width="1476" alt="image" src="https://github.com/micronaut-projects/micronaut-core/assets/49317/fcabd44e-1f5f-4a7b-9553-68460fc3d912">

Is that not what you see?

2023-11-10 17:47 UTC, wetted commented
> @wetted running `./gradlew docs -x htmlSanityCheck` locally, I see
> 
> <img alt="image" width="1476" src="https://user-images.githubusercontent.com/49317/282136190-fcabd44e-1f5f-4a7b-9553-68460fc3d912.png">
> Is that not what you see?

No. Probably a caching issue on my mac. I'll check it again

2023-11-10 19:51 UTC, wetted commented
@timyates thanks for checking. It is a chace issue with Chrome on my Mac. I see it just fine with Safari and Firefox, so I'm good with that.

2023-11-11 08:42 UTC, graemerocher approved these changes

2023-11-13 14:30 UTC, merged