Remove warning about Logbook bug
micronaut-projects/micronaut-core pull request #10118
Opened 2023-11-14 17:04 UTC by msdousti

The official documentation mentions a **major bug** for Logbook:

![image](https://github.com/micronaut-projects/micronaut-core/assets/3616518/ac79919a-9bbf-45f5-a323-676d5f3eaa3c)

It refers to [this issue](https://github.com/zalando/logbook/issues/1216) on the Logbook project, which has been fixed by [this PR](https://github.com/zalando/logbook/pull/1538), and integrated into [Logbook 3.1.0](https://github.com/zalando/logbook/compare/3.0.0...3.1.0) on May 19, 2023.

As such, I'd like to suggest removing this waning from the documentation. Thanks!

2023-11-14 17:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=10118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=10118) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-core?pullRequest=10118) it.</sub>

2023-11-24 05:54 UTC, sdelamo approved these changes
I have updated logbook which we use in the test classpath to 3.6.0

2023-11-24 06:23 UTC, sdelamo commented
Test `def 'h2c do not upgrade` fails after upgrading to the latest logbook. @yawkat could you check it out?

2023-12-06 13:46 UTC, yawkat commented
ive merged 4.2.x and now the logbook test suite tests fail

2023-12-06 16:30 UTC, msdousti commented
The `h2c do not upgrade` test is failing because of these lines:

https://github.com/micronaut-projects/micronaut-core/blob/0530ff704695dedee4d614f2e6cb2e055a6128dc/test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyServerCustomizerSpec.groovy#L338-L339

As explained in the description of the PR, with new Logbook version (3.1 onwards), this bug is resolved, so the "second" `bar` should now be visible in the logs. I'll adapt the test.

For some other reason, another test `tls alpn http 2` started to fail after merging `4.2.x` onto this branch. I bumbed Logbook version on `4.2.x` itself and the test passed. A bit strange...

2023-12-07 07:07 UTC, yawkat requested changes

2023-12-07 07:07 UTC, yawkat commented on test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyServerCustomizerSpec.groovy
> -    @Requires(property = 'spec.name', value = 'LogbookNettyServerCustomizerSpec')
this should stay

2023-12-07 07:08 UTC, yawkat commented on test-suite/src/test/groovy/io/micronaut/docs/netty/LogbookNettyServerCustomizerSpec.groovy
> -    @Requires(property = 'spec.name', value = 'LogbookNettyServerCustomizerSpec')
let me check why `tls alpn http 2` is fixed by this

2024-10-07 12:41 UTC, yawkat commented
@msdousti can you sign the CLA?

2024-10-07 16:44 UTC, msdousti commented
@yawkat Signed.

2024-10-07 16:45 UTC, yawkat commented
Thanks!

2024-10-07 16:45 UTC, merged