Only add content-length if the request type permits a body.
micronaut-projects/micronaut-core pull request #10211
Opened 2023-12-05 09:00 UTC by pbthorste

Currently, `DefaultHttpClient.java` sends a `Content-Length: 0` for GET requests. This can cause issues, for example in AWS ALBs, which will most often refuse the request.

For more info on the AWS ALB issue, see https://stackoverflow.com/questions/77288320/aws-application-load-balancer-rejecting-requests-with-content-length-0

The PR makes sure that the content-length header is not included for requests that do not permit a body, such as GET requests.

2023-12-05 10:17 UTC, sdelamo requested changes
Can you use `HttpMethod::permitsRequestBody` instead?

2023-12-05 10:58 UTC, pbthorste commented
@sdelamo The method you mention is actually how the boolean `permitsBody` is created, before being sent to the `buildNettyRequest` method, which reads the value and then uses it to decide whether or not to set a body.
(see lines nr. 1488 and 1560 )

I guess the code could be changed to make this clearer. It could be argued that the `buildNettyRequest` method does not really need the permitsBody parameter since it could figure it out itself by reading the request object. But it is `protected` so maybe changing the signature of the method could be risky.

2023-12-05 13:01 UTC, sdelamo commented
@timyates can you write a http client tck test which verifies the current behavior of the HTTP Header Content-Length for POST and GET requests?

2023-12-06 17:27 UTC, sdelamo commented
@pbthorste we are incorporating your patch here: https://github.com/micronaut-projects/micronaut-core/pull/10218

2023-12-06 17:27 UTC, closed without merging