Avoid having `TypeConverter` defined as beans
micronaut-projects/micronaut-core pull request #10315
Opened 2024-01-02 14:36 UTC by dstepanov

2024-01-02 17:16 UTC, dstepanov commented
Strange, what is defining it to be initiated at the runtime:
```
 Error: Classes that should be initialized at run time got initialized during image building:
 io.micronaut.http.server.cors.CorsOriginConverter was unintentionally initialized at build time. To see why io.micronaut.http.server.cors.CorsOriginConverter got initialized use --trace-class-initialization=io.micronaut.http.server.cors.CorsOriginConverter
 ```

2024-01-03 11:39 UTC, sdelamo requested changes
What is the motivation for this change? 

But more importantly, we need to update the documentation. We currently say: 

> You can register additional converters for types not supported by Micronaut by defining beans that implement the [TypeConverter](https://docs.micronaut.io/latest/api/io/micronaut/core/convert/TypeConverter.html) interface

However, this PR indicates the recommended approach is to:
 Create a class, not a bean, implementing `TypeConveterRegistrar`.
 Register the converter in that class.
 List the `TypeConverterRegistrar` implementation in `src/main/resources/META-INF/services/io.micronaut.core.convert.TypeConverterRegistrar` so that it is loaded later via Java SPI.

Moreover, removing the beans `SameSiteConverter` and `CorsOriginConveter` and making them `@Internal` could be considered a breaking change.

2024-01-03 11:39 UTC, sdelamo commented on http-server/src/main/java/io/micronaut/http/server/ConvertersRegistrar.java
> + * The HTTP server type converters registrar.
I think we should rename to `HttpServerTypeConverterRegistrar`.

2024-01-03 11:39 UTC, sdelamo commented on http/src/main/java/io/micronaut/http/ConvertersRegistrar.java
> +public final class ConvertersRegistrar implements TypeConverterRegistrar {
I think we should rename this class to `HttpTypeConveterRegistrar`.

2024-01-03 12:09 UTC, dstepanov commented
Registering the converter using the SPI versus finding beans should be faster for the startup; having fewer beans is also a plus.

The only reason to have converters as beans is if you need to inject something external. I'm not sure what the point of having those public.

Now I tried to disable `CorsOriginConverter`, and it looks like it's not needed anyway and probably added in v1 because the configuration beans were not flexible enough.

2024-01-03 12:17 UTC, sdelamo commented
> Now I tried to disable `CorsOriginConverter`, and it looks like it's not needed anyway and probably added in v1 because the configuration beans were not flexible enough.

Or maybe we lack test coverage.

2024-01-03 12:18 UTC, sdelamo commented
> The only reason to have converters as beans is if you need to inject something external

What do you mean by `something external`?

2024-01-03 12:21 UTC, dstepanov commented
> > The only reason to have converters as beans is if you need to inject something external
> 
> What do you mean by `something external`?

Like the bean context or something from it.

2024-01-03 12:21 UTC, dstepanov commented
> > Now I tried to disable `CorsOriginConverter`, and it looks like it's not needed anyway and probably added in v1 because the configuration beans were not flexible enough.
> 
> Or maybe we lack test coverage.

I think it's used in the multiple CORS configuration and we should have tests for it.

2024-01-03 12:48 UTC, graemerocher approved these changes

2024-01-03 13:06 UTC, sdelamo commented
> > > Now I tried to disable `CorsOriginConverter`, and it looks like it's not needed anyway and probably added in v1 because the configuration beans were not flexible enough.
> > 
> > 
> > Or maybe we lack test coverage.
> 
> I think it's used in the multiple CORS configuration and we should have tests for it.

A TCK test fails: 

  JUnit Platform Suite:HTTP Server TCK for Netty:JUnit Jupiter:CorsSimpleRequestTest:corsSimpleRequestForLocalhostCanBeAllowedViaRegexConfiguration()

2024-01-03 13:07 UTC, sdelamo commented
@dstepanov can you please update the documentation 
> we need to update the documentation. We currently say:
> 
> > You can register additional converters for types not supported by Micronaut by defining beans that implement the [TypeConverter](https://docs.micronaut.io/latest/api/io/micronaut/core/convert/TypeConverter.html) interface
> 
> However, this PR indicates the recommended approach is to: Create a class, not a bean, implementing `TypeConveterRegistrar`. Register the converter in that class. List the `TypeConverterRegistrar` implementation in `src/main/resources/META-INF/services/io.micronaut.core.convert.TypeConverterRegistrar` so that it is loaded later via Java SPI.

2024-01-03 13:31 UTC, dstepanov commented
It's strange that it would fail only in native

2024-01-03 15:16 UTC, dstepanov commented
@sdelamo I have corrected docs

2024-01-04 17:06 UTC, sdelamo approved these changes

2024-01-04 17:06 UTC, merged