Support accessing enum values annotations
micronaut-projects/micronaut-core pull request #10581
Opened 2024-03-06 12:21 UTC by dstepanov

2024-03-06 13:44 UTC, yawkat approved these changes

2024-03-06 15:55 UTC, graemerocher requested changes

2024-03-06 15:55 UTC, graemerocher commented on core/src/main/java/io/micronaut/core/beans/EnumBeanIntrospection.java
> +    List<EnumConstant<E>> getConstants();
add `@NonNull`

2024-03-06 15:55 UTC, graemerocher commented on core/src/main/java/io/micronaut/core/beans/EnumBeanIntrospection.java
> + * @since 4.4
`@since 4.4.0`

2024-03-06 15:55 UTC, graemerocher commented on core/src/main/java/io/micronaut/core/beans/EnumBeanIntrospection.java
> +        E getValue();
add a nullability annotation to the return value

2024-03-06 15:55 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableEnumBeanIntrospectionAndReference.java
> +public abstract class AbstractInitializableEnumBeanIntrospectionAndReference<E extends Enum<E>> extends AbstractInitializableBeanIntrospectionAndReference<E> implements EnumBeanIntrospection<E> {
shorten this name it is getting a bit crazy

2024-03-06 15:55 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableEnumBeanIntrospectionAndReference.java
> +    public record EnumConstantRef<E extends Enum<E>>(E value, AnnotationMetadata annotationMetadata) implements EnumConstant<E> {
does it need to be public?

2024-03-06 15:55 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableEnumBeanIntrospectionAndReference.java
> +    protected AbstractInitializableEnumBeanIntrospectionAndReference(Class<E> beanType,
add javadoc

2024-03-06 15:55 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableEnumBeanIntrospectionAndReference.java
> +public abstract class AbstractInitializableEnumBeanIntrospectionAndReference<E extends Enum<E>> extends AbstractInitializableBeanIntrospectionAndReference<E> implements EnumBeanIntrospection<E> {
add `@Internal`

2024-03-06 16:33 UTC, dstepanov commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableEnumBeanIntrospectionAndReference.java
> +    public record EnumConstantRef<E extends Enum<E>>(E value, AnnotationMetadata annotationMetadata) implements EnumConstant<E> {
It's referenced from the writer

2024-03-07 07:38 UTC, graemerocher approved these changes

2024-03-07 10:10 UTC, merged