application/x-yaml -> application/yaml
micronaut-projects/micronaut-core pull request #10613
Opened 2024-03-16 06:27 UTC by altro3

See https://www.rfc-editor.org/rfc/rfc9512.html

Fixed #10586

2024-03-18 16:16 UTC, sdelamo requested changes
this is a breaking change.

2024-04-08 05:06 UTC, sdelamo requested changes
Please, document the breaking change in the documentation.

2026-02-22 04:50 UTC, altro3 commented
@sdelamo @graemerocher done

2026-02-23 15:52 UTC, sdelamo approved these changes

2026-02-23 15:52 UTC, merged