Update conditionalBeans.adoc to clarify how to depend on a conditional bean
micronaut-projects/micronaut-core pull request #10760
Opened 2024-04-24 16:21 UTC by mikehearn

Fixes #10757

2024-04-24 18:03 UTC, graemerocher commented on src/main/docs/guide/ioc/conditionalBeans.adoc
> +The link:{api}/io/micronaut/context/annotation/Requires.html[Requires] annotation provides the ability to define one or many conditions on a bean. If a bean is used somewhere but it's requirements ar
`Optional<Bean>` shouldn't really be used although it is supported. Generally `Optional` should only be used for return values. You can use `BeanProvider<Bean>` which provides the same functionality as `Optional`

2024-04-24 18:18 UTC, mikehearn commented on src/main/docs/guide/ioc/conditionalBeans.adoc
> +The link:{api}/io/micronaut/context/annotation/Requires.html[Requires] annotation provides the ability to define one or many conditions on a bean. If a bean is used somewhere but it's requirements ar
Done, PTAL

2024-04-26 09:28 UTC, mikehearn commented
@graemerocher Done, PTAL.

2024-04-29 05:46 UTC, sdelamo approved these changes

2024-05-03 10:12 UTC, sdelamo requested changes

2024-05-03 10:12 UTC, sdelamo commented on src/main/docs/guide/ioc/conditionalBeans.adoc
> +The link:{api}/io/micronaut/context/annotation/Requires.html[Requires] annotation provides the ability to define one or many conditions on a bean. If a bean is used somewhere but it's requirements ar
```suggestion
The link:{api}/io/micronaut/context/annotation/Requires.html[Requires] annotation provides the ability to define one or many conditions on a bean.

If you declare an injection point, for example, `Bean a`, but no bean of type `Bean` can be instantiated, the framework throws a `NoSuchBeanException`.
The framework cannot inject a bean into an injection point if the bean requirements specified by `@Requires` are not fulfilled.

If you want to declare an injection point as Optional, you have several options:

* Mark the injection point as `@Nullable`. In Kotlin, nullable type names have `?` at the end; you don't need to specify the `@Nullable` annotation.
* Declare it as `BeanProvider<Bean>`. Learn about <<types, Injectable Container Types>>.

You can also inject a collection of beans. For example, you can inject `List<Bean>`. The collection is empty if no bean of type `Bean` fulfills the injection point.

=== @Requires Example
```

2024-05-03 10:13 UTC, sdelamo commented on src/main/docs/guide/ioc/conditionalBeans.adoc
> +The link:{api}/io/micronaut/context/annotation/Requires.html[Requires] annotation provides the ability to define one or many conditions on a bean. If a bean is used somewhere but it's requirements ar
@mikehearn what do you think about 👆🏻 ?

2024-05-03 20:48 UTC, mikehearn commented
@sdelamo OK, accepted.

2024-05-04 15:15 UTC, graemerocher approved these changes

2024-05-04 15:16 UTC, merged