Make behaviour of @DefaultImplementation consistent
micronaut-projects/micronaut-core pull request #10820
Opened 2024-05-13 16:36 UTC by graemerocher

2024-05-14 11:46 UTC, sdelamo requested changes
I think this change is a good idea but we should document this in the "Default Implementation" section of the docs. We should mention that @Primary still has precedence over @DefaultImplementation

2024-05-14 15:33 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
> +            if (candidate.hasStereotype(DefaultImplementation.class)) {
Checking the first candidate should be enough to know if there is a default impl

2024-05-16 08:55 UTC, dstepanov commented
Personally, I don't like the idea of `@DefaultImplementation` defined on the interface, considering this can be implemented with priority.

I think this will not work correctly in a case `class SomeImpl{X,Y, Z} extends SomeBase; abstract class SomeBase implements ISomeWithDefault` and injecting `SomeBase`. The correct way would be to use some annotation processing to map the class name on which the annotation is applied to `@DefaultImplementation`  and check if the inject point is trying to resolve that class.

2024-05-16 12:38 UTC, graemerocher commented
right, I added this because the current implementation is confusing and because Guice supports this concept https://github.com/google/guice/blob/2b37f020862e45be58f246a63c2f97fdaff0d433/core/test/com/google/inject/ImplicitBindingTest.java#L54

The example you mention should work fine, we just need to make sure the implementing type matches the type to be injected.

If we don't agree to this change then I can maybe implement is some other way in the Guice bridge, but I would then suggest we deprecate `@DefaultImplementation` all together because the only place it is used is with `@Replaces` and the name and behaviour are very misleading

2024-05-16 13:11 UTC, dstepanov commented
I'm OK with this. Does it work to not have any scope defined on the implementation like it's in the JavaDoc of `DefaultImplementation`?

2024-05-16 13:11 UTC, dstepanov approved these changes

2024-05-16 13:17 UTC, graemerocher commented
yes it does

2024-05-17 10:36 UTC, sdelamo approved these changes

2024-05-17 10:36 UTC, merged