Small performance improvements
micronaut-projects/micronaut-core pull request #10845
Opened 2024-05-21 12:26 UTC by dstepanov

2024-05-21 12:52 UTC, graemerocher approved these changes

2024-05-22 09:51 UTC, altro3 commented
@dstepanov could you revert changes in MediaType? I added them here: https://github.com/micronaut-projects/micronaut-core/pull/10846  so as not to solve problems with conflicts later

2024-05-22 11:41 UTC, yawkat requested changes

2024-05-22 11:41 UTC, yawkat commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
I highly doubt this makes any difference

2024-05-22 11:41 UTC, yawkat commented on core/src/main/java/io/micronaut/core/util/StringUtils.java
> +import org.jetbrains.annotations.NotNull;
wrong annotation

2024-05-22 11:41 UTC, yawkat commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
> +                    System.arraycopy(params, 0, constructorParams, 0, constructorLength);
same here

2024-05-22 12:22 UTC, dstepanov commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
I see reflection access because of `Array.newInstance(newType.getComponentType(), newLength);`

2024-05-22 12:24 UTC, yawkat commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
Even after JIT? copyOf is an intrinsic method

2024-05-22 12:33 UTC, dstepanov commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
<img width="1585" alt="Screenshot 2024-05-22 at 14 32 54" src="https://github.com/micronaut-projects/micronaut-core/assets/666879/2a72d146-76f0-4066-8f01-940eb8089195">

2024-05-23 12:08 UTC, merged

2024-06-01 08:38 UTC, yawkat commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
does not look like reflection

2024-06-01 08:53 UTC, altro3 commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/21839fa7-89ec-46e8-9526-c183f849ceca)
```java
Array.newInstance(newType.getComponentType(), newLength);
```
@dstepanov So, this method doesn't use reflection. If you look to the `Array.newInstance` method, you will see this:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/d8b38513-c3f5-492a-88d5-1609d332af67)
 and
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/2ca3026d-4a82-4ad0-9424-3f8cbd860d04)

@yawkat But I agree with @dstepanov , his code is faster than `Array.copyOf`

2024-06-04 13:19 UTC, dstepanov commented on core/src/main/java/io/micronaut/core/propagation/PropagatedContextImpl.java
> +        System.arraycopy(elements, 0, newElements, 0, elements.length);
It doesn't, but it does access some `reflect` packages that might trigger the creation of reflection metadata. Jonas is right; the method is marked for being replaced with a native method, but somehow, JVM has a problem deciding to remove it.