Add config option for DNS resolution modes
micronaut-projects/micronaut-core pull request #10937
Opened 2024-07-02 15:04 UTC by yawkat

Fixes LMP-266

2024-07-02 15:08 UTC, graemerocher requested changes

2024-07-02 15:08 UTC, graemerocher commented on http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
> +    public enum DnsResolutionMode {
add `@since`  to the new methods and enums

2024-07-02 15:08 UTC, graemerocher commented on http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
> +        bootstrap.resolver(resolverGroup);
should we allow injecting a custom `AddressResolverGroup` using DI so users can override?

2024-07-08 09:52 UTC, yawkat commented on http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java
> +        bootstrap.resolver(resolverGroup);
I've added an option

2024-07-08 09:54 UTC, graemerocher approved these changes

2024-07-08 10:50 UTC, merged