Support binding RouteMatch in server filter methods
micronaut-projects/micronaut-core pull request #10961
Opened 2024-07-09 09:26 UTC by yawkat

This PR adds support for RouteMatch parameters to server filter methods.

Unfortunately, binding was previously fixed for the server and client. This code had no access to RouteMatch (http does not depend on router). I refactored the code to move the arg binding into BaseFilterProcessor. This is then overridden in the server implementation to add RouteMatch binding support.

I also moved ServerHttpRequest binding there while I was at it.

I've tried to keep the move limited. Most of the arg binding code is still in MethodFilter. This avoids having to expose a dozen private classes.

Fixes #10942

2024-07-09 10:52 UTC, dstepanov commented
Looks overcomplicated. We can simple remove restriction: `if (annotationMetadata.hasStereotype(Bindable.class))` because it's being ignored in `BaseFilterProcessor` anyway. And add some inherited method in `BaseFilterProcessor`.

2024-07-09 11:13 UTC, yawkat commented
@dstepanov it's not possible to skip filter execution for non-routematch requests that way. it'd have to involve some changes to the binding logic that i'd rather avoid

2024-07-09 11:20 UTC, graemerocher requested changes

2024-07-09 11:20 UTC, graemerocher commented on router/src/main/java/io/micronaut/web/router/ServerFilterRouteBuilder.java
> +                            builder.addFilterCondition(ctx -> ctx.request().getAttribute(HttpAttributes.ROUTE_MATCH).isPresent());
shouldn't this always be conditional? I mean why would you want an error from the filter if there is not `RouteMatch`? Also this seems to indicate that `null` will never be passed.

2024-07-09 11:20 UTC, graemerocher commented on router/src/main/java/io/micronaut/web/router/ServerFilterRouteBuilder.java
> +                        return (FilterArgBinder) ctx -> ctx.request().getAttribute(HttpAttributes.ROUTE_MATCH).orElse(null);
should probably be `orElseThrow()` and some internal server error or something

2024-07-09 11:20 UTC, graemerocher commented on http/src/main/java/io/micronaut/http/filter/MethodFilter.java
> +        } else if (argumentType == FilterContinuation.class) {
might be good to cleanup all of this `if/else` into individual binders

2024-07-09 11:20 UTC, graemerocher commented on http-server-tck/src/main/java/io/micronaut/http/server/tck/tests/filter/RequestFilterTest.java
> +        public void requestFilterRouteMatch(MutableHttpRequest<?> request, RouteMatch<?> routeMatch) {
If we are keeping the nullable case it needs a test

2024-07-09 12:07 UTC, dstepanov commented
@yawkat Just create a new interface 

```java

interface FilterPredicate {

boolean test(MutablePropagatedContext mutablePropagatedContext,
        HttpRequest<?> request,
        @Nullable HttpResponse<?> response,
        @Nullable Throwable failure)

}

```

If `ArgumentBinder` implements `FilterPredicate` then convert it to `Predicate<FilterMethodContext>`

2024-07-09 12:39 UTC, yawkat commented on router/src/main/java/io/micronaut/web/router/ServerFilterRouteBuilder.java
> +                            builder.addFilterCondition(ctx -> ctx.request().getAttribute(HttpAttributes.ROUTE_MATCH).isPresent());
nullable -> no condition -> filter is executed even for static resources (with null as the arg)

not nullable -> condition -> filter is not executed for static resources (orElse is never hit)

2024-07-16 15:10 UTC, yawkat commented
got a bit more ugly because i have to check for nullability as well, but it works

2024-07-19 12:10 UTC, dstepanov approved these changes

2024-07-19 12:13 UTC, graemerocher commented
@yawkat can you add documentation?

2024-07-19 13:40 UTC, yawkat commented
@graemerocher it's documented in RequestFilter and ResponseFilter where we also document all the other supported argument types

2024-07-19 13:42 UTC, graemerocher approved these changes

2024-07-19 13:42 UTC, merged