#9607: Endpoint path must support URI path as per rfc3986 appendix-B
micronaut-projects/micronaut-core pull request #10998
Opened 2024-07-19 06:17 UTC by pragyamutluru

Fixes https://github.com/micronaut-projects/micronaut-core/issues/9607
I have referred to DefaultUriBuilder.STRING_PATTERN_PATH to change the regex being checked in AbstractEndpointRouteBuilder.ENDPOINT_ID_PATTERN.

2024-07-19 06:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=10998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=10998) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-core?pullRequest=10998) it.</sub>

2024-07-19 07:00 UTC, sdelamo commented
@pragyamutluru you need to sign the contributor license agreement

2024-07-22 09:04 UTC, yawkat requested changes

2024-07-22 09:04 UTC, yawkat commented on management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
> +    private static final Pattern ENDPOINT_ID_PATTERN = Pattern.compile("([^#?]*)");
I think this is too wide. 
```suggestion
    private static final Pattern ENDPOINT_ID_PATTERN = Pattern.compile("[\\w-]+");
```

2024-07-22 12:00 UTC, graemerocher commented on management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
> +    private static final Pattern ENDPOINT_ID_PATTERN = Pattern.compile("([^#?]*)");
Agreed, what pattern do you suggest?

2024-07-22 13:54 UTC, pragyamutluru commented on management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
> +    private static final Pattern ENDPOINT_ID_PATTERN = Pattern.compile("([^#?]*)");
Updated code to narrow down the check as per suggestion. Kindly check the latest change.

2024-07-23 06:25 UTC, yawkat approved these changes

2024-07-23 12:04 UTC, graemerocher approved these changes

2024-07-23 12:04 UTC, merged

2024-07-23 12:04 UTC, graemerocher commented
Thanks for the contribution!