Add API to access main context from bootstrap context
micronaut-projects/micronaut-core pull request #11065
Opened 2024-08-09 14:21 UTC by yawkat

This is the least intrusive change I could come up with. The idea is that bootstrap beans can register singletons in the main context, and then normal beans can access those singletons to share data with the bootstrap.

2024-08-09 14:31 UTC, graemerocher requested changes

2024-08-09 14:31 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/BootstrapContextAccess.java
> +public interface BootstrapContextAccess {
also add `@Internal` for now

2024-08-09 14:31 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/BootstrapContextAccess.java
> +    BeanDefinitionRegistry getMainRegistry();
add nullability annotations

2024-08-12 21:10 UTC, sdelamo approved these changes

2024-08-13 07:41 UTC, dstepanov approved these changes

2024-08-13 07:54 UTC, merged