Allow to handle all possible controller errors
micronaut-projects/micronaut-core pull request #11070
Opened 2024-08-12 09:15 UTC by dstepanov

Including errors like incorrect HTTP method, content type etc. Right now it's only possible to catch this kind of error using a status route per status.

This is needed to align with JAX-RS where the exception handler can handle all the exceptions.

2024-08-12 09:16 UTC, dstepanov commented on http-server/src/main/java/io/micronaut/http/server/RequestLifecycle.java
>          if (errorRoute != null) {
Just extracted two methods

2024-08-12 09:49 UTC, yawkat approved these changes

2024-08-12 10:57 UTC, dstepanov commented
Looks like one test is failign because not it triggers:
```
        @Error(exception = RuntimeException)
        HttpResponse onError() {
            HttpResponse.badRequest()
        }
```

2024-08-12 11:49 UTC, dstepanov commented
@yawkat @graemerocher @sdelamo Should there be a configuration option to enable it?

2024-08-12 13:14 UTC, sdelamo requested changes
Can you please ship a default [built-in exception handler](https://docs.micronaut.io/4.5.3/guide/#builtInExceptionHandlers) for `HttpServerException` or `HttpException`?

2024-08-13 07:16 UTC, sdelamo commented
> Looks like one test is failign because not it triggers:
> 
> ```
>         @Error(exception = RuntimeException)
>         HttpResponse onError() {
>             HttpResponse.badRequest()
>         }
> ```

I think we could rewrite the test not to capture such a generic exception: https://github.com/micronaut-projects/micronaut-core/pull/11077

2024-08-13 12:52 UTC, closed without merging