Make `MediaType` comparable
micronaut-projects/micronaut-core pull request #11226
Opened 2024-10-02 09:34 UTC by dstepanov

We can avoid creating a lambda to do sorting

2024-10-02 11:00 UTC, sdelamo approved these changes

2024-10-02 16:36 UTC, graemerocher requested changes

2024-10-02 16:36 UTC, graemerocher commented on http/src/main/java/io/micronaut/http/MediaType.java
> +import org.jetbrains.annotations.NotNull;
use the Micronaut version

2024-10-03 08:19 UTC, graemerocher approved these changes

2024-10-03 08:41 UTC, merged