Update introspection documentation
micronaut-projects/micronaut-core pull request #11240
Opened 2024-10-07 10:31 UTC by ChaimaaeROUAI

Fixing issue #11207

2024-10-08 11:33 UTC, sdelamo requested changes

2024-10-08 11:33 UTC, sdelamo commented on src/main/docs/guide/appendix/architecture/introspectionArch.adoc
> +Many libraries in Java need to programmatically discover what methods represent properties of a class in some way and while the https://en.wikipedia.org/wiki/JavaBeans[JavaBeans specification] tried
```suggestion
Many libraries in Java need to programmatically discover what methods represent properties of a class in some way and whilst the https://en.wikipedia.org/wiki/JavaBeans[JavaBeans specification] tried to establish a standard convention, the language itself has evolved to include other constructs like Records that represent properties as components.
```

2024-10-08 11:33 UTC, sdelamo commented on src/main/docs/guide/appendix/architecture/introspectionArch.adoc
> +Many libraries in Java need to programmatically discover what methods represent properties of a class in some way and while the https://en.wikipedia.org/wiki/JavaBeans[JavaBeans specification] tried
I think `whilst` was correct.

2024-10-08 11:33 UTC, sdelamo commented on src/main/docs/guide/appendix/architecture/introspectionArch.adoc
> +This generation happens via the `io.micronaut.inject.beans.visitor.BeanIntrospectionWriter`, an internal class that uses the ASM bytecode generation library to generate an additional classes.
```suggestion
This generation happens via the `io.micronaut.inject.beans.visitor.BeanIntrospectionWriter`, an internal class that uses the ASM bytecode generation library to generate an additional class.
```

2024-10-08 11:41 UTC, ChaimaaeROUAI commented on src/main/docs/guide/appendix/architecture/introspectionArch.adoc
> +Many libraries in Java need to programmatically discover what methods represent properties of a class in some way and while the https://en.wikipedia.org/wiki/JavaBeans[JavaBeans specification] tried
ah OK I thought It was a typo

2024-10-08 15:08 UTC, sdelamo approved these changes

2024-10-10 11:36 UTC, graemerocher approved these changes

2024-10-10 11:36 UTC, merged