Minor server optimizations
micronaut-projects/micronaut-core pull request #11306
Opened 2024-11-04 11:34 UTC by yawkat

NameUtilsTest takes too long to run as part of the suite, but if we need to optimize another of its methods, it may be useful again.

2024-11-04 12:15 UTC, graemerocher approved these changes

2024-11-04 16:16 UTC, dstepanov requested changes

2024-11-04 16:16 UTC, dstepanov commented on core/src/test/java/io/micronaut/core/naming/NameUtilsTest.java
> +@Disabled
Disabled?

2024-11-05 08:49 UTC, yawkat commented on core/src/test/java/io/micronaut/core/naming/NameUtilsTest.java
> +@Disabled
yep, see PR text :P

2024-11-05 12:33 UTC, merged