Improve event loop locality of client requests
micronaut-projects/micronaut-core pull request #11300
Opened 2024-11-01 14:17 UTC by yawkat

If a request is made on an event loop that is part of the same event loop group that the client is configured to use, prefer making the connection on that same event loop. This keeps all the relevant processing on the same thread and may improve performance.

2024-11-11 12:36 UTC, graemerocher approved these changes

2025-01-22 14:09 UTC, sdelamo commented
@yawkat does this PR still apply?

2025-01-24 09:53 UTC, dstepanov requested changes

2025-01-24 09:53 UTC, dstepanov commented on http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
> +        public @NonNull HttpClientConfiguration.ConnectionPoolConfiguration.ConnectionLocality getConnectionLocality() {
Please add since to the new methods and classes

2025-01-24 09:53 UTC, dstepanov commented on http-client/src/main/java/io/micronaut/http/client/netty/PoolResizer.java
> +        private volatile ResizerConnection[] unsafeItems = EMPTY;
Just use `CopyOnWriteArrayList`

2025-01-24 10:33 UTC, yawkat commented on http-client/src/main/java/io/micronaut/http/client/netty/PoolResizer.java
> +        private volatile ResizerConnection[] unsafeItems = EMPTY;
i want to avoid lock contention in doSomeWork, and it also gives me the option to sort the connections in-place there

2025-01-27 12:39 UTC, merged