Replace HttpAttributes with accessors
micronaut-projects/micronaut-core pull request #11324
Opened 2024-11-07 16:20 UTC by yawkat

Attributes are a suboptimal way of adding metadata to requests and responses, both because they need a string lookup, and because they require conversion.

2024-11-08 05:55 UTC, altro3 commented
@yawkat I think it would be better to add a fix for the missing `SERVICE_ID` attribute in the JDK http client at this point. See: https://github.com/micronaut-projects/micronaut-core/pull/11309

2024-11-08 08:11 UTC, yawkat commented
it's not super important that core code is migrated from HttpAttributes immediately, so #11309 can stay as-is. the main concern is users and non-core micronaut projects.

2025-01-23 14:47 UTC, graemerocher requested changes

2025-01-23 14:47 UTC, graemerocher commented on http-client-core/src/main/java/io/micronaut/http/client/ClientAttributes.java
> +public final class ClientAttributes {
is this regarded public API?

2025-01-23 14:47 UTC, graemerocher commented on http/src/main/java/io/micronaut/http/HttpAttributes.java
> +@Deprecated(forRemoval = true)
add `@since` to all deprecated annotations

2025-01-23 14:57 UTC, yawkat commented on http-client-core/src/main/java/io/micronaut/http/client/ClientAttributes.java
> +public final class ClientAttributes {
Yes

2025-01-23 16:47 UTC, graemerocher approved these changes

2025-01-24 09:49 UTC, dstepanov approved these changes

2025-01-24 12:01 UTC, merged