Minor perf optimizations
micronaut-projects/micronaut-core pull request #11322
Opened 2024-11-07 09:56 UTC by dstepanov

2024-11-07 10:22 UTC, graemerocher requested changes

2024-11-07 10:22 UTC, graemerocher commented on http/src/main/java/io/micronaut/http/MediaType.java
> +    public Map<CharSequence, String> getParametersMap() {
add `@since` and nullability annotations

2024-11-07 10:22 UTC, graemerocher commented on http/src/main/java/io/micronaut/http/util/HttpUtil.java
> +    public static Charset getResolveCharset(HttpMessage<?> request) {
add `@since` and nullability annotations

2024-11-07 10:27 UTC, graemerocher approved these changes

2024-11-07 18:47 UTC, yawkat commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
> +    private static final BiConsumer<String, Object> CLEANUP_ATTRIBUTES = new BiConsumer<>() {
I think it's possible to do this without a variable. put the lambda body in a static method and make it a method reference, then i believe it's cached.

2024-11-07 18:49 UTC, yawkat commented on http/src/main/java/io/micronaut/http/util/HttpUtil.java
> +    public static Charset getResolveCharset(@NonNull HttpMessage<?> request) {
Either call it get or call it resolve

2024-11-07 18:50 UTC, yawkat approved these changes

2024-11-11 07:59 UTC, yawkat commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
> +            attributes.forEach(cleanup());
no it needs to be a method ref, something like NettyHttpRequest::cleanup

2024-11-11 08:04 UTC, yawkat commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
> +            attributes.forEach(cleanup());
Actually, looking at LambdaMetafactory, I think this change is altogether unnecessary: You only need to make releaseIfNecessary static, and the lambda won't capture anything, and will be cached.

2024-11-11 10:32 UTC, yawkat commented
@dstepanov please merge 4.8.x, there were some compilation issues on 4.8.x that i just fixed.

2024-11-11 12:35 UTC, merged