Use sourcegen bytecode generator to generate internal metadata
micronaut-projects/micronaut-core pull request #11407
Opened 2024-12-04 11:56 UTC by dstepanov

The PR rewrites all the class writers (except the evaluated expressions writer) to use a new bytecode generator from Micronaut Sourcegen.

I haven't done any major refactoring. Some classes like `BeanDefnitionWriter` is too big and need some refactoring

2024-12-04 13:15 UTC, graemerocher requested changes

2024-12-04 13:15 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/beans/AbstractInitializableBeanIntrospection.java
> +        }
are these necessary? I would like to avoid another binary incompatible change

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
> +        Map<String, MethodDef> loadTypeMethods = new HashMap<>();
should this be a linked hash map? Will it impact the order of the methods written?

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
> +                    ReflectionUtils.getRequiredMethod(AnnotationMetadataProvider.class, "getAnnotationMetadata")
extract this to a constant, maybe in `AnnotationMetadataGenUtils`

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
>          );
can we shorten this via some factory method like `MethodElement.constructorOf`?

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +                        invocation = ClassTypeDef.of(MethodInterceptorChain.class).instantiate(
extract `ClassTypeDef.of(MethodInterceptorChain.class)` to constant

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +        List<TypeDef> interfaces = new ArrayList<>();
does this need to be a sorted set to avoid duplicates?

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +    private static String toTypeString(ClassElement p) {
this seems like something that belongs in `ClassElement` or a utility method

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
> +        throw new IllegalStateException("Not supported!");
why?

2024-12-04 13:15 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
> +        throw new IllegalStateException("Not supported!");
why?

2024-12-04 14:55 UTC, dstepanov commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +    private static String toTypeString(ClassElement p) {
Not sure, we just do some unique string from a class

2024-12-04 14:57 UTC, dstepanov commented on core-processor/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
> +        throw new IllegalStateException("Not supported!");
It returns asm Type. I will delete those two methods

2024-12-04 15:00 UTC, dstepanov commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
>          );
This is a unique use-case; I would just leave it as it is

2024-12-04 15:01 UTC, dstepanov commented on core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
> +        Map<String, MethodDef> loadTypeMethods = new HashMap<>();
Fixed, it's only used for testing anyway

2025-01-08 12:37 UTC, graemerocher requested changes
we need to make sure that we retain that the generated byte code is synthetic

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +            newConstructorParameters.toArray(ZERO_PARAMETER_ELEMENTS)
would be good to add a `MethodElement.constructorOf` method that makes this simple

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> -        classWriter.visit(V17, ACC_SYNTHETIC, className, null, !isInterface ? superType.getInternalName() : null, interfaces);
make sure that whatever we are generated retains `ACC_SYNTHETIC` modifier. I can't seem to see where this is retained?

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +        int[] index = {0};
maybe the methods of `AtomicInteger` would be more useful for this.

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataGenUtils.java
> +public class AnnotationMetadataGenUtils {
should be `final` with a `private` constructor

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataGenUtils.java
> +public class AnnotationMetadataGenUtils {
can you javadoc public methods and rearrange methods so public methods are first

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/writer/ExpressionsUtils.java
> +public final class ExpressionsUtils {
add a `private` constructor

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/writer/ExpressionsUtils.java
> +public final class ExpressionsUtils {
can we rename this to something else? We already have the concepts of expressions with `#{..}` so might cause confusion

2025-01-08 12:37 UTC, graemerocher commented on core-processor/src/main/java/io/micronaut/inject/writer/MethodGenUtils.java
> +public final class MethodGenUtils {
add a `private` constructor

2025-01-08 12:37 UTC, graemerocher commented on core/src/main/java/io/micronaut/core/reflect/ReflectionUtils.java
> +    public static <R, T> R invokeInaccessibleMethod(T instance, Method method, Object... arguments) {
add `@since`

2025-01-08 12:45 UTC, dstepanov commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> +            newConstructorParameters.toArray(ZERO_PARAMETER_ELEMENTS)
This is a very unique case, I don't see a point of adding a new method

2025-01-08 12:45 UTC, dstepanov commented on core-processor/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
> -        classWriter.visit(V17, ACC_SYNTHETIC, className, null, !isInterface ? superType.getInternalName() : null, interfaces);
Ok, I need to add a support for it first

2025-01-09 10:43 UTC, graemerocher approved these changes

2025-01-09 11:39 UTC, merged