KSP: Fixed method `isEnum()` for KotlinTypeArgumentElement
micronaut-projects/micronaut-core pull request #11422
Opened 2024-12-08 10:51 UTC by altro3

2024-12-08 10:55 UTC, altro3 commented
@dstepanov Review it, pls. Found this problem in simple test in micronaut-openapi:
```kotlin
@Controller("/hello")
class HelloController {

    @Get
    @Produces(MediaType.TEXT_PLAIN)
    fun index(@Nullable @QueryValue("channels") channels: Collection<Channel?>?) = ""

    @Introspected
    enum class Channel {
        @JsonProperty("mysys")
        SYSTEM1,
        SYSTEM2
    }
}
```
When I get `typeArgument` for `Collection` type, I get `KotlinTypeArgumentElement` element, and default `isEnum()` implemention is
```java
    default boolean isEnum() {
        return this instanceof EnumElement;
    }
```

That's why method `isEnum()` returns `false`, but must be `true`

2024-12-09 12:07 UTC, graemerocher approved these changes

2025-01-06 08:31 UTC, dstepanov requested changes

2025-01-06 08:31 UTC, dstepanov commented on inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
> +    override fun isEnum() = declaration.classKind == ClassKind.ENUM_CLASS
This shouldn't be needed. The fix should properly create a`KotlinEnumElement`

2025-01-08 07:06 UTC, altro3 commented on inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
> +    override fun isEnum() = declaration.classKind == ClassKind.ENUM_CLASS
I don't quite understand how you propose to do this? Now when I request a generic for a collection, I get an instance of the `KotlinTypeArgumentElement` class - and this is correct, but I can't figure out that this is an enum, because the check for an enum is `this instanceof EnumElement;`

So it's not clear at what point you propose to get `KotlinEnumElement`

2025-01-08 08:16 UTC, dstepanov commented on inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
> +    override fun isEnum() = declaration.classKind == ClassKind.ENUM_CLASS
Ah in this case, this is correct, but anyway, I think you should always need to call `resolved`

2025-01-08 08:17 UTC, dstepanov approved these changes

2025-01-08 09:28 UTC, altro3 commented on inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
> +    override fun isEnum() = declaration.classKind == ClassKind.ENUM_CLASS
Sorry, I didn't understand your last sentence either. Maybe it's because of the holidays :-)

2025-01-08 09:48 UTC, dstepanov commented on inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
> +    override fun isEnum() = declaration.classKind == ClassKind.ENUM_CLASS
`GenericElement` class has `getResolved`/`resolved` methods to get the actual type represented as generic

2025-01-08 10:00 UTC, altro3 commented on inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/KotlinClassElement.kt
> +    override fun isEnum() = declaration.classKind == ClassKind.ENUM_CLASS
In any case, without this fix, the isEnum method may return incorrect value, as in my case.

2025-01-08 13:57 UTC, merged