Documentation for Custom http status code
micronaut-projects/micronaut-core pull request #11445
Opened 2024-12-15 08:24 UTC by Nitishrajj

This PR is related to the opened issue #11220 
@yawkat, please feel free to provide any suggestions or feedback on the changes. I'm open to any improvements or ideas you may have.

2024-12-15 08:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=11445) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=11445) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-core?pullRequest=11445) it.</sub>

2024-12-17 12:43 UTC, graemerocher commented
it needs to be added to `toc.yml` somewhere for it to appear in the docs

2024-12-17 12:48 UTC, graemerocher requested changes
Thanks, some adjustments needed

2024-12-17 12:48 UTC, graemerocher commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +----
please move all the hard coded snippets into references to actual source code for Groovy, Java and Kotlin using the `snippet::` macro

2024-12-17 12:48 UTC, graemerocher commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +Micronaut now supports arbitrary HTTP status codes that are not part of the predefined `HttpStatus` enum. Developers can specify any valid HTTP status code within the range `100-599`.
```suggestion
Micronaut supports arbitrary HTTP status codes that are not part of the predefined `HttpStatus` enum. Developers can specify any valid HTTP status code within the range `100-599`.
```

2024-12-17 12:48 UTC, graemerocher commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +The Micronaut framework supports Custom HTTP Status Codes . This feature enables developers to define and use HTTP status codes beyond the standard ones, allowing integration with systems or APIs tha
```suggestion
The Micronaut framework supports custom HTTP status codes. This feature enables developers to define and use HTTP status codes beyond the standard ones, allowing integration with systems or APIs that rely on non-standard status codes.
```

2024-12-17 12:48 UTC, graemerocher commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +=== Custom HTTP Status Codes
```suggestion
=== Custom HTTP Status Codes

```

2024-12-17 12:48 UTC, graemerocher commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +The addition of custom HTTP status code support in Micronaut enhances its flexibility, enabling developers to integrate with systems using non-standard codes. With this feature, arbitrary HTTP status
the content is unnecessary and suitable for a blog post but not for user documentation which doesn't need to mention what is was supported before and what is now.

2024-12-23 17:37 UTC, Nitishrajj commented
Sure, working on it.

2024-12-26 14:24 UTC, Nitishrajj commented
I have made the changes and resolved the comments, please feel free to suggest any other changes if needed. 
Thank you.

2024-12-30 08:12 UTC, yawkat commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +The Micronaut framework supports custom HTTP status codes .This feature enables developers to define and use HTTP status codes beyond the standard ones, allowing integration with systems or APIs that
```suggestion
The Micronaut framework supports custom HTTP status codes. This feature enables developers to define and use HTTP status codes beyond the standard ones, allowing integration with systems or APIs that rely on non-standard status codes.
```

2024-12-30 08:13 UTC, yawkat commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +    if (e.getStatus().getCode() == 450) {
```suggestion
    if (e.code() == 450) {
```

2024-12-31 10:47 UTC, yawkat approved these changes

2024-12-31 10:48 UTC, Nitishrajj commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +    if (e.getStatus().getCode() == 450) {
I have made necessary changes, please do check.

2025-01-02 14:39 UTC, graemerocher commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +snippet::io.micronaut.http.HttpResponse[tags="getStatusMethod", indent=0, title="HttpResponse.java"]
Have you tested these snippets actually work?

2025-01-08 09:25 UTC, Nitishrajj commented on src/main/docs/guide/httpServer/customHttpStatusCode
> +snippet::io.micronaut.http.HttpResponse[tags="getStatusMethod", indent=0, title="HttpResponse.java"]
These are all the existing snippets which are released right so did not test.

2025-03-13 09:00 UTC, sdelamo requested changes
`customHttpStatusCode` file should be `customHttpStatusCode.adoc` otherwise documentation fails to build with `./gradlew docs`

2025-03-13 09:02 UTC, sdelamo commented on src/main/docs/guide/httpServer/customHttpStatusCode.adoc
> +=== Custom HTTP Status Codes
```suggestion

=== Custom HTTP Status Codes
```

2025-03-13 09:02 UTC, sdelamo commented on src/main/docs/guide/httpServer/customHttpStatusCode.adoc
> +=== Custom HTTP Status Codes
a new line is necessary before the asciidoc header.

2025-03-13 09:06 UTC, sdelamo requested changes

2025-03-13 09:06 UTC, sdelamo commented on src/main/docs/guide/httpServer/customHttpStatusCode.adoc
> +snippet::io.micronaut.http.client.netty.FullNettyClientHttpResponse[tags="getBodyMethod", indent=0, title="FullNettyClientHttpResponse.java"]
Snippet is for code samples in test-suite, test-suite-groovy and test-suite-kotlin. This does not work. Please, try `./gradlew docs` locally to see if it renders correctly.

2025-03-13 09:10 UTC, sdelamo commented
@Nitishrajj the asciidoc tags, (`getBodyMethod`, and `testInvalidStatus`) which you reference, don't exist in the code base.

2025-03-13 09:23 UTC, sdelamo commented
@Nitishrajj I have simplified the documentation change. Thanks for the contribution.

2025-03-13 09:23 UTC, merged