Support Tracing of Dependency Injection
micronaut-projects/micronaut-core pull request #11449
Opened 2024-12-16 19:36 UTC by graemerocher

- **add debug mode enum**
- **initial implementation system out tracing**
- **add property origin tracking**
- **reduce stacktrace depth of bean context**
- **fix error messags / optimize frames**
- **fix tests and checkstyle**
- **fix tests**

2025-01-07 08:59 UTC, dstepanov requested changes

2025-01-07 08:59 UTC, dstepanov commented on core/src/main/java/io/micronaut/core/type/TypeInformation.java
> +            Optional<String> q = annotationMetadata.getAnnotationNameByStereotype(AnnotationUtil.QUALIFIER)
Maybe you can use similar code to `Qualifiers.forArgument`

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
> +    default @NonNull ApplicationContextBuilder traceMode(@NonNull BeanResolutionTraceMode traceMode) {
Can this be `beanResolutionTrace(@NonNull BeanResolutionTraceMode traceMode, String... classPatterns)`

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/BeanResolutionTraceMode.java
> +    void startTrace(
Can you move all the tracing code into some other class, not to have it in a public enum?

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
> +                    bean = resolveByBeanFactory(resolutionContext, instantiatableBeanDefinition, qualifier, argumentValues);
Don't create a new out-scope variable, just call `return postBeanCreated` right after. Next else is not needed. Same pattern repeats a few times

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/env/Environment.java
> +    @Deprecated(forRemoval = true)
Add since

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/env/PropertySource.java
> +    @Deprecated(forRemoval = true)
Add since

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/env/PropertySource.java
> +    @Deprecated(forRemoval = true)
Add since

2025-01-07 08:59 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/env/PropertySource.java
> +    record PropertyEntry(
Can you convert it to an interface? I don't like the idea of exposing a record as a public API

2025-01-07 08:59 UTC, dstepanov commented
Can you show an example of the output?

2025-01-07 09:01 UTC, dstepanov commented
Maybe one of the outputs can be a flame graph like the async profiler output ![Async profiler output](https://github.com/async-profiler/async-profiler/raw/master/.assets/images/flamegraph.png)

2025-01-13 16:22 UTC, graemerocher commented on core/src/main/java/io/micronaut/core/type/TypeInformation.java
> +            Optional<String> q = annotationMetadata.getAnnotationNameByStereotype(AnnotationUtil.QUALIFIER)
code here is in core which can't reference inject

2025-01-13 16:33 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/BeanResolutionTraceMode.java
> +    void startTrace(
the trace methods are not currently public but package private. In the future yes it would be good to add a public API but for the moment it is package private / internal

2025-01-13 18:06 UTC, graemerocher commented
Example Output 

<img width="1162" alt="Screenshot 2025-01-08 at 08 45 59" src="https://github.com/user-attachments/assets/8ee3200d-67f9-4ca6-9cf1-ea6bb6b92743" />

2025-01-13 18:41 UTC, graemerocher commented
More complex bean resolution debug output of the creation of the DataSource from Micronaut-SQL

<img width="1598" alt="Screenshot 2025-01-13 at 14 41 05" src="https://github.com/user-attachments/assets/71e42374-70a2-47f9-a67f-951f67c14816" />

2025-01-14 13:09 UTC, dstepanov approved these changes

2025-01-14 14:40 UTC, merged