Rename micronaut-discovery-client module group
micronaut-projects/micronaut-core pull request #4243
Opened 2020-10-05 08:14 UTC by pgressa

2020-10-05 08:15 UTC, pgressa commented
Needed in order to address https://github.com/micronaut-projects/micronaut-kubernetes/issues/188

2020-10-05 08:16 UTC, alvarosanchez approved these changes

2020-10-05 09:39 UTC, pgressa commented
There are some failures in tests not caused by this PR:
```
Error: eckstyle] [ERROR] /home/runner/work/micronaut-core/micronaut-core/http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java:77:5: '/*' has more than 1 empty lines before. [EmptyLineSeparator]
```
```
Error: eckstyle] [ERROR] /home/runner/work/micronaut-core/micronaut-core/http-client-core/src/main/java/io/micronaut/http/client/bind/DefaultHttpClientBinderRegistry.java:18:8: Unused import - io.micronaut.context.annotation.BootstrapContextCompatible. [UnusedImports]
```
.....



Is that intentional? @alvarosanchez @graemerocher ?

2020-10-05 10:53 UTC, alvarosanchez commented
Sounds like someone left Checkstyle errors in the base branch

2020-10-05 10:56 UTC, pgressa commented
> Sounds like someone left Checkstyle errors in the base branch

I'll append a commit with fixes ..

2020-10-05 15:03 UTC, pgressa commented
Plust the test `RequestCertificateSpec` is failing on expired certificate so I'm going to update the keystore

2020-10-05 16:31 UTC, ilopmar commented
@pgressa please take a look at what I've tried (unsuccessfully): https://github.com/micronaut-projects/micronaut-servlet/issues/75#issuecomment-703737157

2020-10-05 17:42 UTC, pgressa commented
> Plust the test `RequestCertificateSpec` is failing on expired certificate so I'm going to update the keystore

2020-10-06 10:47 UTC, graemerocher requested changes
Does this not need to go into 2.1.x as well?

2020-10-06 10:47 UTC, graemerocher commented on http-server-netty/src/test/resources/logback.xml
> +    <logger name="sun.security" level="TRACE"/>
Please remove this logback changes

2020-10-06 11:18 UTC, pgressa commented on http-server-netty/src/test/resources/logback.xml
> +    <logger name="sun.security" level="TRACE"/>
sure, forgot them ..

2020-10-06 19:41 UTC, pgressa commented
@graemerocher any other comments?

2020-10-08 07:30 UTC, merged