fix: protect against npe thrown by nullable bean context
micronaut-projects/micronaut-core pull request #4575
Opened 2020-11-20 10:53 UTC by sdelamo

I am getting a NPE: 

```
Caused by: java.lang.NullPointerException: null
	at io.micronaut.aop.chain.InterceptorChain.resolveAroundInterceptors(InterceptorChain.java:246)
	at uk.co.metadataworks.auth.repository.$UserRepositoryProviderImplDefinition$Intercepted.<init>(Unknown Source)
```

This is an extract from `UserRepositoryProviderImpl` bean:

```
@Singleton
public class UserRepositoryProviderImpl implements UserRepositoryProvider {
    private final BeanContext beanContext;
    private final TenantResolver tenantResolver;
    private final Map<String, UserRepository> userRepository = new ConcurrentHashMap<>();

    public UserRepositoryProviderImpl(BeanContext beanContext, TenantResolver tenantResolver) {
        this.beanContext = beanContext;
        this.tenantResolver = tenantResolver;
    }
```

2020-11-20 15:45 UTC, jameskleeh requested changes
We shouldn't change the methods to start accepting nulls when they previously did not. Instead pass `getClass().getClassLoader()` if bean context is null

2020-11-20 16:20 UTC, sdelamo commented
I can do what you suggest but I think given that this was a [7 days ago change](https://github.com/micronaut-projects/micronaut-core/pull/4471/files). I personally think it is a bug and we should  considering fixing the method signature to reflect the nullability. 

Do you feel strongly that `default Optional<Class<? extends Annotation>> getAnnotationType(@NonNull String name, @NonNull ClassLoader classLoader)` should be `@NonNull`?

2020-11-20 16:22 UTC, jameskleeh commented
The signature that should be changed is the one that takes a `BeanContext`. It currently does not have `@Nullable` even though null is possible. That is why this issue wasn't caught.

2020-11-28 14:22 UTC, sdelamo commented
I cannot call `getClass().getClassLoader());` in `InterceptorChain::resolveIntroductionInterceptors` because it is a static method. I've moved classLoader resolution to  `AnnotationMetadataDelegate` the first non static method in the chain.

2020-11-30 07:27 UTC, graemerocher commented
This is the incorrect fix, not all implementations of `AnnotationMetadata` would necessarily implement `AnnotationMetadataDelegate`

You can use `InterceptorChain.class.getClassLoader()` instead of `getClass().getClassLoader()`

2020-12-02 08:58 UTC, sdelamo commented
I've done the change you suggested @graemerocher

2020-12-02 11:40 UTC, merged