Standard behavior for ConstraintViolationException
micronaut-projects/micronaut-core pull request #4644
Opened 2020-12-01 14:36 UTC by rafaelrenanpacheco

When `ConstraintExceptionHandler` is thrown, all violation messages will be serialized in the `_embedded.errors` array, like this:

```json
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/users",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "userCreateRequest.name: must not be blank"
      }
    ]
  }
}
```

```json
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/users",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "userCreateRequest.name: must not be blank"
      },
      {
        "message": "userCreateRequest.email: must not be blank"
      }
    ]
  }
}
```

For more details take a loot at #4616.

- Fixes #4616

2020-12-01 14:48 UTC, graemerocher commented
This could be regarded as a breaking change for users that parse errors although it is clearly a more consistent fix. Thoughts @jameskleeh ?

2020-12-01 14:50 UTC, jameskleeh commented
@graemerocher I think its better to gate this behind a config option and then remove the option or change the default for 3.0

2020-12-01 15:06 UTC, graemerocher commented
Right

2020-12-01 15:22 UTC, rafaelrenanpacheco commented
Hello!

In order to gate this behind a config option (application.properties), is there an specific way to read this config from the micronaut-core point of view?

I know how to read properties from an user point of view, a simple @Value or property mapper can achieve that, but I don't know if this is the expected way to do on micronaut-core.

2020-12-01 15:59 UTC, jameskleeh commented
@rafaelrenanpacheco We use `@ConfigurationProperties` beans to read config

2020-12-01 16:02 UTC, rafaelrenanpacheco commented
Thanks @jameskleeh!

I'll look for some examples using `@ConfigurationProperties` and update this PR later today.

2020-12-02 02:36 UTC, rafaelrenanpacheco commented
I think it is ready.

![sweating](https://user-images.githubusercontent.com/12160864/100820917-0ca1c380-342e-11eb-89bf-e090f64e0866.gif)

2020-12-02 06:53 UTC, graemerocher requested changes

2020-12-02 06:53 UTC, graemerocher commented on validation/src/main/java/io/micronaut/validation/exceptions/ConstraintExceptionHandler.java
> +    }
To avoid a breaking API change please restore the no argument constructor and annotate this one with `@Inject`

2020-12-02 06:53 UTC, graemerocher commented on runtime/src/main/java/io/micronaut/jackson/serialize/OptionalValuesSerializer.java
> +    }
To avoid a breaking API change please restore the no argument constructor and annotate this one with `@Inject`

2020-12-02 06:53 UTC, graemerocher commented on runtime/src/main/java/io/micronaut/jackson/serialize/OptionalValuesSerializer.java
> +        return type != JsonError.class || !jacksonConfiguration.getHateoas().isAlwaysSerializeErrorsAsList();
Please assign `jacksonConfiguration.getHateoas().isAlwaysSerializeErrorsAsList()` to a final local field to avoid repeated method calls

2020-12-02 06:53 UTC, graemerocher commented on validation/src/main/java/io/micronaut/validation/exceptions/ConstraintExceptionHandler.java
> +        } else if (constraintViolations.size() == 1 && !jacksonConfiguration.getHateoas().isAlwaysSerializeErrorsAsList()) {
Please assign `jacksonConfiguration.getHateoas().isAlwaysSerializeErrorsAsList()` to a final local field to avoid repeated method calls

2020-12-02 06:53 UTC, graemerocher commented on runtime/src/main/java/io/micronaut/jackson/JacksonConfiguration.java
> +    }
I don't think we need a whole new nested config props just for this. Adding the field at the top level is fine

2020-12-03 07:49 UTC, graemerocher requested changes

2020-12-03 07:49 UTC, graemerocher commented on validation/src/main/java/io/micronaut/validation/exceptions/ConstraintExceptionHandler.java
> +    private JacksonConfiguration jacksonConfiguration;
private field injection requires reflection, please change this to a field representing the configuration and use constructor injection and then add an additional constructor to maintain compatibility. Something like:

```java
private final boolean alwaysSerializeErrorsAsList;

@Inject
public ConstraintExceptionHandler(JacksonConfiguration jacksonConfiguration) {
       this. alwaysSerializeErrorsAsList = jacksonConfiguration.isAlwaysSerializeErrorsAsList();
}

public ConstraintExceptionHandler() {
      this.alwaysSerializeErrorsAsList = true
}
```

2020-12-03 07:49 UTC, graemerocher commented on runtime/src/main/java/io/micronaut/jackson/serialize/OptionalValuesSerializer.java
> +    private JacksonConfiguration jacksonConfiguration;
private field injection requires reflection, please change this to a field representing the configuration and use constructor injection and then add an additional constructor to maintain compatibility. Something like:

```java
private final boolean alwaysSerializeErrorsAsList;

@Inject
public OptionalValuesSerializer(JacksonConfiguration jacksonConfiguration) {
       this. alwaysSerializeErrorsAsList = jacksonConfiguration.isAlwaysSerializeErrorsAsList();
}

public OptionalValuesSerializer() {
      this.alwaysSerializeErrorsAsList = true
}
```

2020-12-03 16:33 UTC, merged

2020-12-03 16:33 UTC, graemerocher commented
Thanks for the contribution!