Trim strings when deserializing
micronaut-projects/micronaut-core pull request #4679
Opened 2020-12-07 22:29 UTC by rafaelrenanpacheco

Hello!

This PR creates a new property that enables an automatic trim on strings during deserialization.

If `jackson.trim-strings` is set to `true`, then the following payload

```json
{
  "id": 1,
  "email": " abc ",
  "name": " Micronaut ",
  "city": " ",
  "active": true,
  "createdAt": "2020-01-31"
}
```

will have the strings trimmed to null before attributing them to a pojo. It would be the equivalent of sending the following request:

```json
{
  "id": 1,
  "email": "abc",
  "name": "Micronaut",
  "city": null,
  "active": true,
  "createdAt": "2020-01-31"
}
```

By default this feature is disabled. If trim is desired, then `jackson.trim-strings` must be set to `true`.

Thanks @jameskleeh for the snippet.

- Fixes #4675

2020-12-07 23:36 UTC, rafaelrenanpacheco commented
I had to add the following dependencies to test the string trim through a json request to a controller:

```groovy
testImplementation project(":http-server-netty")
testImplementation project(":http-client")
```

This broke the [ExecutorServiceConfigSpec](https://github.com/micronaut-projects/micronaut-core/blob/2.2.x/runtime/src/test/groovy/io/micronaut/runtime/executor/ExecutorServiceConfigSpec.groovy) tests:

- `executorServices.size() == 4` is now `5`
- `ctx.getBean(ThreadPoolExecutor, Qualifiers.byName("one"))` don't find any bean with this name.

Any hints on what went wrong here?

2020-12-08 14:43 UTC, jameskleeh requested changes
Instead of having a Pojo and adding dependencies to the server and client, simply add a test in `JacksonSetupSpec` that passes in JSON with strings and assert they are trimmed

2020-12-08 14:43 UTC, jameskleeh commented on runtime/src/main/java/io/micronaut/jackson/deserialize/StringTrimModule.java
> +@Requires(property = "jackson.trim-strings", value = StringUtils.TRUE)
There needs to be a field/getter/setter for this in `JacksonConfiguration`

2020-12-08 14:43 UTC, jameskleeh commented on runtime/src/main/java/io/micronaut/jackson/deserialize/StringTrimModule.java
> +        addDeserializer(String.class, new StringDeserializer() {
This should probably be done within the `ObjectMapperFactory` and then you can check for `jacksonConfiguration.getTrimStrings()`

2020-12-08 23:56 UTC, rafaelrenanpacheco commented
Hello @jameskleeh, thanks for the suggestions, things are much simpler now.

But, there is a problem.

The deserializer is being beaned and being [picked here](https://github.com/micronaut-projects/micronaut-core/blob/186d434c66e3d9215a40de6647ccf513b7b54907/runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java#L120).

The problem is, this deserializer is not being using during [this test](https://github.com/micronaut-projects/micronaut-core/blob/9f8b6814eea60edffcc2d3a0582ee74da7f1108d/runtime/src/test/groovy/io/micronaut/jackson/JacksonSetupSpec.groovy#L136-L151).

I tried extending `StdDeserializer`, `JsonDeserializer`, and even using `extends SimpleModule`, the latter being [picked here](https://github.com/micronaut-projects/micronaut-core/blob/186d434c66e3d9215a40de6647ccf513b7b54907/runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java#L90), but none of them actually run the `deserialize()` method.

I tried to debbug the `ObjectMapper` as well, but didn't find any place that tries to choose these deserializers, even tho they are configured through the `ObjectMapperFactory`.

There is a `BigDecimalDeserializer extends JsonDeserializer<BigDecimal>` in the micronaut-core that is just a `@Singleton` and I suppose it works just fine.

Any clue on what I might be missing?

Thanks.

2020-12-09 19:14 UTC, jameskleeh commented
@rafaelrenanpacheco I took the PR and moved it forward here https://github.com/micronaut-projects/micronaut-core/pull/4696

2020-12-09 19:14 UTC, closed without merging

2020-12-09 19:46 UTC, rafaelrenanpacheco commented
Thanks @jameskleeh!