adding optional idle timeout to http client connection pool channels
micronaut-projects/micronaut-core pull request #4780
Opened 2021-01-06 20:53 UTC by drmaas

2021-01-06 20:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=4780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=4780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-core?pullRequest=4780) it.</sub>

2021-01-07 07:46 UTC, graemerocher requested changes
A few changes, and looks like there is a failing test. Probably a concurrency issue

2021-01-07 07:46 UTC, graemerocher commented on http-client/src/main/java/io/micronaut/http/client/netty/IdleTimeoutHandler.java
> +public final class IdleTimeoutHandler extends ChannelDuplexHandler {
Missing `@author` and `@since` tags and I think this class can be package/private and annotated with `@Internal`

2021-01-07 07:46 UTC, graemerocher commented on http-client/src/main/java/io/micronaut/http/client/netty/IdlingConnectionHandler.java
> +public final class IdlingConnectionHandler extends ChannelInboundHandlerAdapter {
Missing `@author` and `@since` tags and I think this class can be package/private and annotated with `@Internal`

2021-01-07 07:46 UTC, graemerocher commented on http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
> +                if (ch.pipeline().context(IdlingConnectionHandler.INSTANCE) != null) {
Maybe extra `pipeline()` to a local variable to avoid multiple calls

2021-01-07 07:46 UTC, graemerocher commented on http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
> +                    ch.pipeline().addLast(IdlingConnectionHandler.INSTANCE);
Maybe extra `pipeline()` to a local variable to avoid multiple calls

2021-01-11 20:06 UTC, drmaas commented
@graemerocher updated per comments

2021-01-14 15:20 UTC, merged

2021-01-14 15:20 UTC, graemerocher commented
Thanks for the contribution!