provider changes
micronaut-projects/micronaut-core pull request #5156
Opened 2021-03-20 10:56 UTC by graemerocher

2021-03-25 21:05 UTC, jameskleeh requested changes
I think this needs tests to assert the behavior of `@Any` for non BeanProvider use cases to assert what happens with multiple beans of different orders, same order, and no beans.

2021-03-25 21:05 UTC, jameskleeh commented on inject/src/main/java/io/micronaut/context/BeanProvider.java
> +     * @return true if no bean matches.
This javadoc is wrong it seems.

2021-03-25 21:10 UTC, jameskleeh commented on inject/src/main/java/io/micronaut/context/BeanProvider.java
> +     * Is the bean resolvable.
Perhaps expand on this to indicate what resolvable means

2021-03-25 21:11 UTC, jameskleeh commented on inject/src/main/java/io/micronaut/context/BeanProvider.java
> +     * Executes the given logic if the bean is present.
This should probably explain that in the case of multiple beans only the first one is passed

2021-03-26 10:38 UTC, graemerocher commented
I have not yet implemented the part where `@Order` is taken into account to select the bean that will come in a second PR. 

Addressed the other feedback and for the moment merging this one.

2021-03-26 11:44 UTC, merged