Improve bean context startup performance
micronaut-projects/micronaut-core pull request #5352
Opened 2021-04-30 16:13 UTC by dstepanov

Custom fork-join implementation performs much better than a parallel stream.
On my machine, a simple http app startup goes from best ~750ms to ~650ms.

2021-04-30 16:45 UTC, dstepanov commented
Parallel processing might not be needed for Graal

2021-04-30 18:41 UTC, graemerocher approved these changes

2021-05-01 08:01 UTC, graemerocher requested changes

2021-05-01 08:01 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
> +    protected @NonNull List<BeanDefinitionReference> resolveBeanDefinitionReferences(Predicate<BeanDefinitionReference> predicate) {
Can we retain the original signature and delegate just in case to avoid the breaking change

2021-05-01 08:01 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
> +        Collection<BeanDefinition<T>> candidates = super.findBeanCandidates(resolutionContext, beanType, filterProxied, predicate);
Same here

2021-05-01 08:01 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
> +            List<BeanDefinitionReference> refs = super.resolveBeanDefinitionReferences(null);
Same here

2021-05-05 14:06 UTC, merged