Delegate bean resolution context when resolving non-lazy proxy target
micronaut-projects/micronaut-core pull request #6058
Opened 2021-08-24 13:39 UTC by dstepanov

Added a check not to cache proxies in `DefaultBeanContext` `scopedProxies` for `@Any` bean producers, not sure if we should cache anything as it can leak the instance for some short-lived scopes.

2021-08-24 18:37 UTC, jameskleeh commented on aop/src/main/java/io/micronaut/aop/chain/ConstructorInterceptorChain.java
> +                    originalParameters.length - 4
How would this work with old style bean definitions? Couldn't this break with those definitions?

2021-09-01 12:22 UTC, dstepanov commented
I have added a way to pass the number of added constructor parameters in proxies that should solve the backward compatibility issue.

Implemented bean resolution context storing and propagating for lazy interceptor target beans.

Also added double-check locking to cache the target in lazy beans: 

```java
    public Object interceptedTarget() {
        ProxiedSomeBeanConsumer var1 = this.$target;
        if (var1 == null) {
            synchronized(this) {
                var1 = this.$target;
                if (var1 == null) {
                    this.$target = (ProxiedSomeBeanConsumer)((DefaultBeanContext)this.$beanLocator).getProxyTargetBean(this.$beanResolutionContext, Argument.of(ProxiedSomeBeanConsumer.class, $ProxiedSomeBeanConsumer$Definition$Intercepted$Definition$Reference.$ANNOTATION_METADATA, new Class[0]), this.$beanQualifier);
                    this.$beanResolutionContext = null;
                }
            }
        }

        return this.$target;
    }
 ```

2021-09-01 12:50 UTC, graemerocher commented
@dstepanov tests are failing, those need addressing before review

2021-09-01 13:39 UTC, dstepanov commented
It looks like caching target cannot be done by default.
I have added an option `@Around(cacheableLazyTarget)` to preserve the work I did

2021-09-10 07:57 UTC, graemerocher requested changes

2021-09-10 07:57 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
> +    private class DefaultBeanResolutionContext extends AbstractBeanResolutionContext {
Rename to `SingletonBeanResolutionContext` since there is already a `DefaultBeanResolutionContext` in `io.micronaut.context`

2021-09-10 13:41 UTC, merged