WebSocket ping API [Adds #5680]
micronaut-projects/micronaut-core pull request #6294
Opened 2021-10-07 07:45 UTC by yawkat

This API is mostly parallel to the normal message API. To stay consistent with javax.websocket, methods annotated with `@OnMessage` are used as pong handlers if they have a `WebSocketPongMessage` argument.

A `sendPingAsync` method was added to `WebSocketSession` to allow sending a ping.

Neither of these APIs does the type conversion that the normal message handling does. In my opinion it does not make much sense for ping/pong messages – you might want to put a timestamp into the message, but that's about it.

2021-10-07 09:06 UTC, graemerocher requested changes

2021-10-07 09:06 UTC, graemerocher commented on http-netty/src/main/java/io/micronaut/http/netty/websocket/NettyWebSocketSession.java
> +            ByteBuf messageBuffer = channel.alloc().buffer(content.length);
Does this need releasing  when the future completes?

2021-10-07 09:06 UTC, graemerocher commented on http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java
> +                }
Please add compilation time validation as well. See https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/http-validation/src/main/java/io/micronaut/validation/websocket/WebSocketVisitor.java

2021-10-07 09:06 UTC, graemerocher commented on http-client/src/main/java/io/micronaut/http/client/netty/websocket/NettyWebSocketClientHandler.java
> +
Please add compilation time validation as well. See https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/http-validation/src/main/java/io/micronaut/validation/websocket/WebSocketVisitor.java

2021-10-07 09:06 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +public final class WebSocketPongMessage {
Add `@since`

2021-10-07 09:06 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +    public WebSocketPongMessage(ByteBuffer<?> content) {
Maybe a no arguments constructor with an empty content is required as well, seems like sending a body is optional?

2021-10-07 09:06 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +    public ByteBuffer<?> getContent() {
Add nullability annotations

2021-10-07 09:06 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketSession.java
> +    default CompletableFuture<?> sendPingAsync(byte[] content) {
Add nullable annotations and `@since`

2021-10-07 09:06 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketSession.java
> +    default CompletableFuture<?> sendPingAsync(byte[] content) {
Do we need `ByteBuffer` variants?

2021-10-07 09:06 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/context/WebSocketBean.java
> +    default Optional<MethodExecutionHandle<T, ?>> pongMethod() {
Add `@since`

2021-10-07 09:08 UTC, yawkat commented on http-netty/src/main/java/io/micronaut/http/netty/websocket/NettyWebSocketSession.java
> +            ByteBuf messageBuffer = channel.alloc().buffer(content.length);
The channel should take care of it I think, since it's being written

2021-10-07 09:10 UTC, yawkat commented on http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java
> +                }
Will do, will be fairly limited though because OnMessage validation should already do it

2021-10-07 09:11 UTC, yawkat commented on http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java
> +                }
Actually, the existing OnMessage checks already cover this completely. The only thing this code adds is check that the parameter is WebSocketPongMessage, but if it isn't, it'll just be used as a normal message handler

2021-10-07 09:14 UTC, yawkat commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +    public WebSocketPongMessage(ByteBuffer<?> content) {
Yes, netty does this. How can I create an empty ByteBuffer though, since this is in the module without netty?

It's also not that important, because this class is really only constructed by the actual websocket handler, not by users.

2021-10-07 09:16 UTC, yawkat commented on websocket/src/main/java/io/micronaut/websocket/WebSocketSession.java
> +    default CompletableFuture<?> sendPingAsync(byte[] content) {
Not sure, the only thing the implementation could do with a ByteBuffer is copy it using toByteArray anyway. There could be a special case for a ByteBuffer<ByteBuf> but right now I do a defensive copy anyway (is that sensible?)

2021-10-07 10:55 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +    public WebSocketPongMessage(ByteBuffer<?> content) {
One option would be to allow content to be `@Nullable` and return an `Optional`

2021-10-07 10:55 UTC, graemerocher commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +    public WebSocketPongMessage(ByteBuffer<?> content) {
But yes I get your point about it being not that important, does it make sense to mark this class as `@Internal` in that case?

2021-10-07 11:58 UTC, yawkat commented on websocket/src/main/java/io/micronaut/websocket/WebSocketPongMessage.java
> +    public WebSocketPongMessage(ByteBuffer<?> content) {
Well the class is still used as a parameter type, users just wouldn't create instances on their own. The constructor could be internal

2021-10-08 17:21 UTC, jameskleeh commented
Needs documentation

2021-10-09 05:00 UTC, yawkat commented
Converted to draft, should go into 3.2.x branch once it's created.

@jameskleeh Do you mean more javadoc, or actual website docs? I'd need to read up how to do it for the latter.

2021-10-09 05:01 UTC, jameskleeh commented
Website docs

2021-10-12 02:13 UTC, jameskleeh commented
Rebase against 3.2.x

2021-10-19 07:00 UTC, yawkat commented
I've added a note for the `WebSocketPongMessage` parameter for `@OnMessage` methods.

In my opinion, adding the ping api to the example snippet in the guide is not sensible, because it is fairly niche and would just add noise for most users. But as-is, this API isn't very discoverable, so not sure how to proceed here.

2021-10-20 16:01 UTC, merged