add jaeger support for codec
micronaut-projects/micronaut-core pull request #6535
Opened 2021-11-18 22:11 UTC by manuelmartinoracle

Fixes https://github.com/micronaut-projects/micronaut-core/issues/6389

2021-11-18 22:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=6535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=6535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-core?pullRequest=6535) it.</sub>

2021-11-19 17:04 UTC, graemerocher commented
Please correct the checkstyle errors

2021-11-22 09:57 UTC, pgressa requested changes
Good job, please remove commented code and address the code review comments.

2021-11-22 09:57 UTC, pgressa commented on test-suite/src/test/groovy/io/micronaut/tracing/jaeger/JaegerConfigurationSpec.groovy
> +    /**
we don't add author annotation for tests

2021-11-22 09:57 UTC, pgressa commented on test-suite/src/test/groovy/io/micronaut/tracing/jaeger/JaegerConfigurationSpec.groovy
> +        /*
remove commented code

2021-11-22 09:57 UTC, pgressa commented on tracing/src/main/java/io/micronaut/tracing/jaeger/JaegerConfiguration.java
> +     * @author Manuel Martin
we don't add author annotation to methods, move it to the class javadoc

2021-11-22 09:57 UTC, pgressa commented on tracing/src/main/java/io/micronaut/tracing/jaeger/JaegerConfiguration.java
> +    @ConfigurationProperties("codec")
I don't think it's necessary to add a new configuration property class that encapsulates just one string field. Is there a problem to have the `codec` (`codecs`) to be part of `JaegerConfiguration` ?

2021-11-22 09:57 UTC, pgressa commented on test-suite/src/test/groovy/io/micronaut/tracing/jaeger/JaegerConfigurationSpec.groovy
> +        def config = ctx.getBean(JaegerConfiguration.JaegerCodecConfiguration).getCodecConfiguration()
could the subject of test be the `io.jaegertracing.Configuration` aka `JaegerConfiguration#getConfiguration` ?

2021-11-23 16:42 UTC, pgressa requested changes
Good job @manuelmartinoracle ! could you please extend the documentation as well https://docs.micronaut.io/latest/guide/#jaeger,  thank you!

2021-12-01 16:33 UTC, pgressa approved these changes

2021-12-01 17:05 UTC, merged