Add JsonMapper-based readMetadataUrl method to ComputeInstanceMetadataResolverUtils
micronaut-projects/micronaut-core pull request #6587
Opened 2021-11-30 10:22 UTC by yawkat

This allows loading metadata with only the json-core module. The other methods require jackson-core or jackson-databind.

Required for micronaut-aws migration.

2021-11-30 11:37 UTC, graemerocher requested changes

2021-11-30 11:37 UTC, graemerocher commented on runtime/src/main/java/io/micronaut/discovery/cloud/ComputeInstanceMetadataResolverUtils.java
> +     * @throws IOException if any I/O error occurs
Add `@since`

2021-11-30 13:30 UTC, graemerocher approved these changes

2021-12-02 15:56 UTC, jameskleeh commented
This should go into 3.3

2021-12-03 13:54 UTC, graemerocher commented
@jameskleeh normally I would agree but it would be nice if the all the modules were compatible with serialization for the release of Micronaut 3.3.

Without this method then AWS module will not work with Micronaut Serialization and is coupled to Jackson until 3.3 is out and we will have to do a patch release of AWS afterwards

If you think that is better then we do that, but seems a pretty minor change to wait all the way until 3.3.1

2022-01-27 17:04 UTC, merged