Create new netty-graal module for native image configuration
micronaut-projects/micronaut-core pull request #6657
Opened 2021-12-14 15:33 UTC by yawkat

The graal configuration that netty needs was previously only present in the http-netty module (HttpNettyFeature). This patch creates a new netty-graal module for that configuration, so that other modules that use netty but not http-netty (in particular micronaut-grpc) can use the same configuration.

Resolves #6650

2021-12-17 11:01 UTC, ilopmar requested changes
I've tried this locally with the gRPC module and everything works as expected

2021-12-17 11:01 UTC, ilopmar commented on netty-graal/src/main/java/io/micronaut/netty/NettyFeature.java
> +final class NettyFeature implements Feature {
I'd add here `@Internal`

2021-12-17 11:01 UTC, ilopmar commented on settings.gradle
> +include 'netty-graal'
Sorry to be picky here but we are using double-quotes `"` instead of single-quote `'` :see_no_evil:

2021-12-17 11:05 UTC, ilopmar commented
I've created https://github.com/micronaut-projects/micronaut-grpc/pull/437 in gRPC module with the changes to use this once we release Micronaut 3.3.0

2021-12-17 11:14 UTC, graemerocher commented
I am still unconvinced a new module needed. Especially if https://github.com/micronaut-projects/micronaut-core/pull/6661 is merged in which case that module will be need to allow configurability of the Netty buffer allocator

2021-12-29 08:35 UTC, yawkat commented
Then #6661 should also be in the new module

2021-12-30 10:37 UTC, graemerocher commented
Why? it relates to configuring the buffer allocator and is in the netty-buffer module. What more appropriate module would it live in? Configuring the buffer allocator seems something that would be desirable in a gRPC app as well

2021-12-30 10:46 UTC, yawkat commented
imo the purpose of the netty-buffer module is to provide the netty implementation of `io.micronaut.core.io.buffer.ByteBuffer`, general netty configuration is unrelated

2022-01-10 08:33 UTC, yawkat commented
moved this to buffer-netty too, as per #6661

2022-01-24 19:18 UTC, merged