Do not insert `@RequestAttribute`s as path params
micronaut-projects/micronaut-core pull request #6718
Opened 2022-01-07 10:28 UTC by yawkat

a3c46be7bf2cb6fc91a90985e767fb4f19782b8d introduced the possibility of using `@RequestAttribute` parameters as path parameters. However, path parameters that aren't explicitly bound are inserted as query parameters, so the `@RequestAttribute` is inadvertently leaked.

This change reverts back to the old behavior.

Fixes #6717

2022-01-07 13:58 UTC, graemerocher approved these changes

2022-01-07 19:09 UTC, jameskleeh requested changes
In general I agree with the change but I think instead of breaking the existing use case we can maintain the current behavior and fix the current bug by checking if a variable exists in the template.

```
            conversionService.convert(value, ConversionContext.STRING.with(context.getAnnotationMetadata()))
                    .filter(StringUtils::isNotEmpty)
                    .ifPresent(param -> {
                        String pathName = context.getArgument().getName();
                        if (uriContext.getUriTemplate().getVariableNames().contains(pathName)) {
                            uriContext.getPathParameters().put(pathName, param);
                        }
                    });
```

2022-01-10 08:06 UTC, yawkat commented
good idea, done.

2022-01-10 14:18 UTC, jameskleeh approved these changes

2022-01-10 14:18 UTC, merged