feat: adds LocalizedMessageSource
micronaut-projects/micronaut-core pull request #6870
Opened 2022-02-04 11:12 UTC by sdelamo

- It makes MessageSource Ordered since CompositeMessageSource attempts to order the MessageSource beans.
- It shows the recommended approach of using a factory to create a MessageSource with a ResourceBundleMessageSource
- It adds extra default methods to MessageSource to make it easier to work with the API.

2022-02-07 13:05 UTC, timyates approved these changes
LGTM 👍 

I [tweaked the whitespace](https://github.com/micronaut-projects/micronaut-core/pull/6870/commits/de7a93515a862191b6a3b8ff92a8caa92452894a) a bit in one of the tests, hope that's ok

2022-02-07 14:36 UTC, jameskleeh requested changes

2022-02-07 14:36 UTC, jameskleeh commented on http/build.gradle
> -
Why was this block removed?

2022-02-07 14:36 UTC, jameskleeh commented on inject/src/main/java/io/micronaut/context/MessageSourceUtils.java
> +            variables.put("" + count, value);
Why not use `String.valueOf`  ?

2022-02-07 14:36 UTC, jameskleeh commented on inject/src/main/java/io/micronaut/context/MessageSourceUtils.java
> + * @since 3.4.x
Should be 3.4.0

2022-02-07 17:32 UTC, sdelamo commented on http/build.gradle
> -
it was duplicated.

2022-02-07 17:34 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/MessageSourceUtils.java
> + * @since 3.4.x
Changed

2022-02-07 17:34 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/MessageSourceUtils.java
> +            variables.put("" + count, value);
Resolved via https://github.com/micronaut-projects/micronaut-core/pull/6870/commits/e47ba8bcf985e69a8068d7a1c604d1711beff48d

2022-02-08 10:38 UTC, graemerocher requested changes

2022-02-08 10:38 UTC, graemerocher commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
The return value should never be `null` but the code as written it could be, probably need to be able to return a default locale if non is available

2022-02-08 10:38 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/LocalizedMessageSource.java
> +public interface LocalizedMessageSource {
Needs type level javadoc. 

I am not sure I understand the need for this interface when we already have the `MessageSource` API which supports passing in a Locale. What is problematic about that API that requires a whole new interface?

2022-02-08 12:04 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/LocalizedMessageSource.java
> +public interface LocalizedMessageSource {
The motivation for this interface is to create a nicer API to work with. 

It is much nicer from a developer point of view to do in a controller: 

```java
@Controller 
class Books {
    private LocalizedMessageSource messageSource;
    public Books(LocalizedMessageSource localizedMessageSource messageSource) {
        this.messageSource = messageSource;
    }

   @Produces(MediaType.TEXT_PLAIN)
   @GET
   String index() {
		return messageSource.get(“book.title”, “Books”);

   }
}
```

than:

```java
@Controller 
class Books {
    private MessageSource messageSource;
    private HttpLocaleResolver httpLocaleResolver;
    public Books(MessageSource messageSource,
                 HttpLocaleResolver httpLocaleResolver) {
        this.messageSource = messageSource;
        this.httpLocaleResolver = httpLocaleResolver;
    }

   @Produces(MediaType.TEXT_PLAIN)
   @GET
   String index(HttpRequest<?> request) {
		return messageSource.get(“book.title”, “Books”, httpLocaleResolver.resolveOrDefault());

   }
}
```

Don’t you think?

2022-02-08 12:13 UTC, sdelamo commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
I injected `HttpLocaleResolutionConfiguration` to set a default locale in the constructor.

 As I understood by being `RequestAware` the `setRequest` method would be called when the object was created and hence the locale was set. 

But I think now it is safer

2022-02-08 12:13 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/LocalizedMessageSource.java
> +public interface LocalizedMessageSource {
> Needs type level javadoc.
Done

2022-02-08 15:22 UTC, jameskleeh commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
We know the request will be set so I don't see the nullability as a concern. If it is null you could throw an exception as that should never happen and keep the contract as NonNull

2022-02-08 15:50 UTC, sdelamo commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
I kept the contract as `@NonNull`. What I have done is set in the constructor as well.

2022-02-08 15:55 UTC, jameskleeh commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
Right but that is wrong imo. We can't assume the default is coming from that configuration. We can only rely on the contract of the interface

2022-02-08 16:26 UTC, sdelamo commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
What exception do you want me to throw if request is null?

2022-02-08 16:50 UTC, jameskleeh commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
IllegalStateException

2022-02-08 18:38 UTC, sdelamo commented on http-server/src/main/java/io/micronaut/http/server/util/locale/HttpLocalizedMessageSource.java
> +        return locale;
fixed via https://github.com/micronaut-projects/micronaut-core/pull/6870/commits/a7359f01a21447439d4d1469b9466ad2e603a290

2022-02-09 14:55 UTC, jameskleeh approved these changes

2022-02-09 15:26 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/LocalizedMessageSource.java
> +public interface LocalizedMessageSource {
@graemerocher are you ok with this?

2022-02-16 13:39 UTC, merged