Release unwrapped body in NettyHttpRequest
micronaut-projects/micronaut-core pull request #6891
Opened 2022-02-09 14:26 UTC by yawkat

This is an attempt at a fix for the flaky FuzzyInputSpec. Can't reproduce that locally, but this code is obviously buggy, so this might help.

`body` is a memoized supplier, but `NettyHttpRequest.release` checks whether it's a reference counted object. The supplier is never reference counted, but the object it supplies might be. This patch stores the unwrapped value as a separate field so that it can be released properly.

The test for #6712 still passes, so this doesn't seem to regress the issue that the patch that caused this leak fixed.

2022-02-09 14:45 UTC, jameskleeh requested changes

2022-02-09 14:45 UTC, jameskleeh commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
> +        if (bodyUnwrapped instanceof ReferenceCounted) {
bodyUnwrapped would need to be set in the `setBody(T body)` method as well no?

2022-02-09 15:18 UTC, yawkat commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
> +        if (bodyUnwrapped instanceof ReferenceCounted) {
yes will fix

2022-02-10 15:44 UTC, merged

2022-02-13 21:10 UTC, rbhambhra commented
@[yawkat](https://github.com/yawkat)
I get the following netty error in version 3.3.1 (not in 3.3.0) and eventually a crash due to OOM

`2022-02-12T03:33:52.301 41624 ERROR [default-nioEventLoopGroup-1-7] [default-nioEventLoopGroup-1-7] [] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
`
Perhaps its fixed by your commit - will try it out when it is released

thanks
Rahul

2022-02-14 08:09 UTC, yawkat commented
Buffer leaks can happen due to many things, not necessarily related to this PR. They shouldn't cause an OOM though.