Allow fully incremental compilation
micronaut-projects/micronaut-core pull request #7195
Opened 2022-04-08 13:56 UTC by graemerocher

2022-04-09 00:34 UTC, jameskleeh commented
Looks OK to me, but it begs the question whether Micronaut 4 is a good time to break binary compatibility. There is a bit of cruft with the old bean definition style, using javax.inject in annotation metadata, and many other places.

2022-04-09 00:35 UTC, jameskleeh approved these changes

2022-04-10 16:10 UTC, melix approved these changes
Changes LGTM!

2022-04-10 16:10 UTC, melix commented on buildSrc/src/main/groovy/io.micronaut.build.internal.sanity-checks.gradle
> +//    finalizedBy(verifyServiceCount)
I think this check can be removed now. It never failed since we switched to forked compilation.

2022-04-10 16:10 UTC, melix commented on test-suite/src/functionalTest/groovy/io/micronaut/context/ApplicationContextConfigurerSpec.groovy
> -        hasServiceFileFor(BeanDefinitionReference) {
Maybe add a new fixture to test this.

2022-04-11 12:28 UTC, graemerocher commented
@jameskleeh just wanted to note this change doesn't break binary compatibility. Old modules still load fine following this change.

2022-04-11 13:47 UTC, graemerocher commented
Note, I can't really improve the coverage as the code is in build-time / GraalVM classes which is impossible to cover

2022-04-12 08:15 UTC, graemerocher commented
hold off merging the graal visitor is still a problem

2022-04-21 05:49 UTC, sdelamo requested changes

2022-04-21 05:49 UTC, sdelamo commented on core/src/main/java/io/micronaut/core/graal/GraalReflectionConfigurer.java
> +                if (accessType.contains(TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS)) {
there is an `ALL_DECLARED_CONSTRUCTOR` block below.

Is this correct?

If it is, I would collapse both if statements.

2022-04-21 05:49 UTC, sdelamo commented on core/src/main/java/io/micronaut/core/annotation/ReflectionConfig.java
> +public @interface ReflectionConfig {
Please, document it in [graalServices.adoc](https://github.com/micronaut-projects/micronaut-core/blob/3.4.x/src/main/docs/guide/languageSupport/graal/graalServices.adoc)

2022-04-21 09:01 UTC, sdelamo approved these changes

2022-04-21 09:32 UTC, merged