Bean context improvements and refactoring
micronaut-projects/micronaut-core pull request #7196
Opened 2022-04-09 08:05 UTC by dstepanov

Multiple improvements for CDI implementation:

- Delegate AbstractInitializableBeanDefinition bean context interaction thru BeanResolutionContext, allowing to inject of custom implementations and aggregate dependable beans
- Refactor of DefaultBeanContext to have main getBean methods return the bean definition which CDI impl. might need to determine the scope of the bean. New methods to get bean registration by the bean definition.

Big refactoring of bean context:
- Extract everything related to the singleton into one class to reduce the size of `DefaultBeanContext`
- Changed how singletons are stored, instead of multiple entries of argument-qualifier keys now there is one representation of `BeanDefinition -> BeanRegistration` plus the fast lookup by argument-qualifier
- Removed duplicate logic
- Added correct `stop` context cleanup, which also spotted a few tests that were using the context after it's been closed
- Extracted some methods to make code more readable

Sonar fixes to introduce generics and simplify methods

2022-04-09 10:42 UTC, dstepanov commented
I did some benchmarking and I see around 5% better startup time

2022-04-09 10:45 UTC, dstepanov commented
Forcing every cache to clean revealed a problem in the Micronaut test:

```
        spec.addCleanupSpecInterceptor(invocation -> {
            afterTestClass(buildContext(invocation, null)); // run some tx stuff
            afterClass(invocation); // context close

            invocation.proceed(); // actual method call
            singletonMocks.clear();
        });
   ```

I think the method call should be before the context close and maybe even before the possible transaction rollback.

2022-04-10 13:46 UTC, graemerocher requested changes
Looks good just a few minor changes. Perhaps try to cleanup as many of the code smells or if you cannot supress them with `@SuppressWarning("java:s24234")` or whatever the sonar number is

2022-04-10 13:46 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/BeanDisposingRegistration.java
> +final class BeanDisposingRegistration<BT> extends BeanRegistration<BT> {
annotate with `@Internal` and add `@author` tag

2022-04-10 13:46 UTC, graemerocher commented on inject/src/main/java/io/micronaut/context/SingletonScope.java
> +final class SingletonScope {
annotate with `@Internal`

2022-04-11 05:06 UTC, dstepanov commented
I don't like the idea of polluting the code with `@SuppressWarning`s just to satisfy Sonar :-/

2022-04-14 11:42 UTC, graemerocher approved these changes

2022-04-19 10:13 UTC, alvarosanchez commented
> I don't like the idea of polluting the code with `@SuppressWarning`s just to satisfy Sonar :-/

Note they can be bulk closed from the Sonar UI.

2022-04-19 10:34 UTC, sdelamo commented on test-suite-jakarta-inject-bean-import/src/test/java/io/micronaut/jakartainject/tck/beanimport/BeanImportTck.java
> +        BeanContext beanContext = BeanContext.run();
I think we should close the `BeanContext`

https://github.com/micronaut-projects/micronaut-core/pull/7233

2022-04-19 10:51 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/NoInjectionBeanDefinition.java
> +final class NoInjectionBeanDefinition<T> implements BeanDefinition<T>, BeanDefinitionReference<T> {
should this be `@Internal`?

2022-04-19 11:00 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/NoInjectionBeanDefinition.java
> +final class NoInjectionBeanDefinition<T> implements BeanDefinition<T>, BeanDefinitionReference<T> {
added

2022-04-19 11:34 UTC, sdelamo approved these changes

2022-04-19 12:50 UTC, merged