Correct Kotlin coroutine interceptions
micronaut-projects/micronaut-core pull request #7247
Opened 2022-04-22 13:27 UTC by dstepanov

Multiple Kotlin coroutine interceptors shouldn't reuse the same future, which leads to incorrect future's callback invocation.

2022-04-22 14:06 UTC, graemerocher approved these changes

2022-04-28 02:45 UTC, sdelamo requested changes

2022-04-28 02:45 UTC, sdelamo commented on test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/InterceptorSpec.kt
> +                println(MyService.events)
remove println statement

2022-04-28 02:46 UTC, sdelamo commented on test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/multiple/InterceptorSpec.kt
> +                println(MyService.events)
resolved via https://github.com/micronaut-projects/micronaut-core/pull/7247/commits/06e807653a575ed98dbde80f365bddc68de67e53

2022-04-28 02:46 UTC, sdelamo approved these changes

2022-04-28 04:20 UTC, merged