fix: @Replaces with qualifier doesn't work (fix #7261)
micronaut-projects/micronaut-core pull request #7274
Opened 2022-04-27 14:48 UTC by ivyazmitinov

2022-04-27 14:50 UTC, ivyazmitinov commented
@dstepanov, Fixed

2022-04-27 15:07 UTC, ivyazmitinov commented
I've also got a bit of the refactoring fever and

- Changed type `Replaces#qualifier` type to the `Class<? extends Annotation> instead of an array. It required a bit of a workaround, but it is a lesser evil, IMO
- Added exception when both `named` and `qualifier` present 

Both changes are meant to streamline the API

2022-04-28 07:50 UTC, ivyazmitinov commented
@graemerocher, I am a bit confused regarding tests: there is a `io.micronaut.docs.replaces.ReplacesTest`, which I've updated with the new use-cases, but there are also a bunch of `io.micronaut.inject.qualifiers.replaces.ReplacesSpec`s. Should I add tests to them as well, or what's best to do?

2022-04-28 17:17 UTC, graemerocher commented
the first one is only for the documentation, the last one is where new and existing tests should be updated yes

2022-04-29 08:09 UTC, ivyazmitinov commented
@graemerocher Done :)

2022-04-29 08:30 UTC, dstepanov requested changes

2022-04-29 08:30 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
> +            if (named.isPresent() || qualifier.isPresent()) {
I would prefer not to have so many `if else` statements, when a block returns the value you don't need to have `else`. Also, I would extract the values only when they are needed:
```
final Optional<String> named = ...
LOG ...
if (named...

Optional<Class<?>> factory
LOG...
if (factory.isPresent() 
etc
```

2022-04-29 08:30 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/annotation/Replaces.java
> +    Class<? extends Annotation> qualifier() default ReplacesQualifierDefaultValue.class;
You can use simple `Annotation.class`

2022-04-29 08:34 UTC, dstepanov commented on inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
> +                if (named.isPresent() && qualifier.isPresent()) {
Here you check if optional is present and then you continue with optional in your code. Please first check if `named` qualifies then if `qualifier` qualifies etc. Preferably reduce the number of lamdas.

2022-04-29 10:27 UTC, ivyazmitinov commented
@dstepanov, Fixed all the issues. 
Also, improved the logging a bit: added additional logs when bean is replaced by any qualifier, and now it writes the log only when a bean was actually replaced.

2022-05-04 07:33 UTC, ivyazmitinov commented
@dstepanov, kind reminder :)

2022-05-04 08:18 UTC, dstepanov commented
@ivyazmitinov Thanks it looks good! One more thing I noticed is that you can replace the stream with a simple loop in this code:

```java
return replacementTypes.stream()
            .filter(isNotTheSameDefinition(definitionToBeReplaced))
            .filter(isNotProxy(definitionToBeReplaced))
            .anyMatch(checkIfReplaces(definitionToBeReplaced, annotationMetadata));
```
We try to use streams as minimal as possible in the core.

Also, now we have the Sonar which unfortunately doesn't run for contributions but it likes to complain about the code style:
```java
if (...) {
 return ...
} else { // not needed else
 return or throw
}
````
It would be nice if you can remove those elses.

2022-05-04 08:42 UTC, ivyazmitinov commented
@dstepanov 
Thanks, will do :) 
And I intentionally refactored the original loop into the stream with fancy predicates, wan't aware about "no streams" policy :) 
What is the issue with them, if you don't mind me asking?

2022-05-04 08:46 UTC, dstepanov commented
We try to not have them in hot paths like a startup (JVM take some time to optimize them) or request processing to reduce allocations.

2022-05-04 10:46 UTC, ivyazmitinov commented
@dstepanov, should be ok now

2022-05-05 09:05 UTC, dstepanov approved these changes

2022-05-18 08:22 UTC, ivyazmitinov commented
@sdelamo, could you, by any chance, take a look at the PR?

2022-05-19 11:45 UTC, sdelamo commented
@ivyazmitinov can you merge 3.5.x into the branch and address the test failures?

2022-05-19 12:54 UTC, ivyazmitinov commented
@sdelamo, done. GraalVM CE CI seems to be unrelated to my changes

2022-05-19 16:51 UTC, merged