Fix proxy with qualifiers and refactor qualifiers code
micronaut-projects/micronaut-core pull request #7305
Opened 2022-05-03 12:40 UTC by dstepanov

The refactoring fixes check if the qualifier is `Named` in some examples:
```
Qualifier<T> declaredQualifier = beanDefinition.getDeclaredQualifier();
boolean propagateQualifier = beanDefinition.isProxy() && declaredQualifier instanceof Named;
```
Now the code is more readable and understandable than before.

2022-05-06 10:33 UTC, graemerocher requested changes

2022-05-06 10:33 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/qualifiers/Utils.java
> +final class Utils {
Can you name this something more specific like `QualifierUtils`

2022-05-06 10:33 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/qualifiers/Utils.java
> +final class Utils {
Also annotate with `@Internal`

2022-05-09 10:46 UTC, graemerocher approved these changes

2022-05-10 08:49 UTC, sdelamo approved these changes

2022-05-10 08:49 UTC, merged