Make DefaultBeanContext#getBeansOfType return all singleton beans reg…
micronaut-projects/micronaut-core pull request #7308
Opened 2022-05-04 12:00 UTC by akorompai

…istered with qualifier

2022-05-10 13:00 UTC, dstepanov approved these changes

2022-05-13 03:50 UTC, sdelamo requested changes

2022-05-13 03:50 UTC, sdelamo commented on .github/release-drafter.yml
> -name-template: Micronaut $NEXT_PATCH_VERSION
why are you deleting this file in this PR? this is unrelated to Fixes https://github.com/micronaut-projects/micronaut-core/issues/7309 ?

2022-05-13 05:02 UTC, sdelamo commented on .github/release-drafter.yml
> -name-template: Micronaut $NEXT_PATCH_VERSION
I restored it here: https://github.com/micronaut-projects/micronaut-core/pull/7308/commits/8a3964715a856258df475b85e3587670e3ee4b16

2022-05-13 05:02 UTC, merged

2022-05-13 05:33 UTC, sdelamo commented
@akorompai thanks for the contribution!