Bump micronaut-test to 3.2.0
micronaut-projects/micronaut-core pull request #7351
Opened 2022-05-12 08:14 UTC by micronaut-build

2022-05-13 04:38 UTC, sdelamo commented
@timyates can you investigate why this is failing?

2022-05-13 10:39 UTC, timyates commented
@sdelamo Please eyeball my changes to ensure I did good 😀👍

2022-05-13 14:45 UTC, sdelamo requested changes

2022-05-13 14:45 UTC, sdelamo commented on gradle/libs.versions.toml
> +jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
remove

2022-05-13 14:45 UTC, sdelamo commented on http-server-netty/build.gradle
> +    testCompileOnly(libs.jetbrains.annotations)
remove

2022-05-13 14:45 UTC, sdelamo commented on gradle/libs.versions.toml
> +jetbrains-annotations = "23.0.0"
remove

2022-05-13 15:02 UTC, timyates commented on gradle/libs.versions.toml
> +jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
So you don't want the `@Language` annotation available here?

https://github.com/micronaut-projects/micronaut-core/blob/019c370f4db0e0aa5517adc8fd8ce4213b8efdb0/http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2ServerPushSpec.groovy#L266-L274

2022-05-13 15:03 UTC, timyates commented on gradle/libs.versions.toml
> +jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
(That's why I added it)

2022-05-13 15:17 UTC, sdelamo commented on gradle/libs.versions.toml
> +jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
I saw that. it is fine. I have removed the rest of the NotNulls https://github.com/micronaut-projects/micronaut-core/pull/7351/commits/0ea1302a9ec7d9ef557b16253f3e3c7aa195bcb1

2022-05-13 15:18 UTC, sdelamo approved these changes

2022-05-15 06:31 UTC, sdelamo approved these changes

2022-05-15 06:31 UTC, merged