Add option to keep request Host header in ProxyHttpClient
micronaut-projects/micronaut-core pull request #7396
Opened 2022-05-16 15:22 UTC by yawkat

Without this patch, the Host header was always cleared and then recomputed from the request URI. This PR adds an overload with an additional boolean flag that if set to true, does not clear the Host header.

Normally I'm not a big fan of such magic flags from a design pov, but I don't see a better solution.

Adds #7158

2022-05-16 15:39 UTC, timyates commented
FYI: We changed to be "on-spec" (and rewrite the header) here https://github.com/micronaut-projects/micronaut-core/pull/6739 after a user raised an issue here https://github.com/micronaut-projects/micronaut-core/issues/3759

2022-05-16 15:40 UTC, yawkat commented
Yes I think the rewrite is usually the correct behavior

2022-05-16 15:43 UTC, graemerocher commented
Can we turn the argument into a `ProxyOptions` type with a builder style? Adding a single flag now means that if we ever need another one if the future it will create a mess of the API

2022-05-17 09:39 UTC, graemerocher requested changes

2022-05-17 09:39 UTC, graemerocher commented on http-client-core/src/main/java/io/micronaut/http/client/ProxyRequestOptions.java
> +public final class ProxyRequestOptions {
Add `@since` and author tags

2022-05-17 09:47 UTC, timyates approved these changes
👍 

Can't think of a way to increase the coverage apart from maybe checking equals() works

But that's probably chasing a statistic, and not adding much value

2022-05-17 10:00 UTC, graemerocher approved these changes

2022-05-17 10:00 UTC, merged