Fix sharing resolution context for bean providers
micronaut-projects/micronaut-core pull request #7583
Opened 2022-06-16 11:01 UTC by dstepanov

Fixes #7581

2022-06-16 13:16 UTC, graemerocher approved these changes

2022-06-16 13:49 UTC, auke- commented on inject/src/main/java/io/micronaut/inject/provider/JakartaProviderBeanDefinition.java
>      protected Provider<Object> buildProvider(BeanResolutionContext resolutionContext, BeanContext context, Argument<Object> argument, Qualifier<Object> qualifier, boolean singleton) {
There are 3 implementations of the `buildProvider` method: JakartaProviderBeanDefinition (this class), JavaxProviderBeanDefinition and BeanProviderDefinition. Their implementation looks very similar, shouldn't JavaxProviderBeanDefinition and BeanProviderDefinition also be changed?

2022-06-16 13:55 UTC, graemerocher requested changes

2022-06-16 13:55 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/provider/JakartaProviderBeanDefinition.java
>      protected Provider<Object> buildProvider(BeanResolutionContext resolutionContext, BeanContext context, Argument<Object> argument, Qualifier<Object> qualifier, boolean singleton) {
Good catch @dstepanov we will need to alter the other impls

2022-06-16 14:39 UTC, dstepanov commented on inject/src/main/java/io/micronaut/inject/provider/JakartaProviderBeanDefinition.java
>      protected Provider<Object> buildProvider(BeanResolutionContext resolutionContext, BeanContext context, Argument<Object> argument, Qualifier<Object> qualifier, boolean singleton) {
Yeah, good catch, pushed fixes for other providers as well

2022-06-17 06:54 UTC, dstepanov commented
I have removed the `javax` test because it requires adding `javax` dependency and that alters other tests.

2022-06-17 07:53 UTC, sdelamo approved these changes

2022-06-17 07:54 UTC, merged