Support static factory methods and fields
micronaut-projects/micronaut-core pull request #7769
Opened 2022-07-29 10:07 UTC by graemerocher

2022-07-29 10:18 UTC, dstepanov approved these changes

2022-07-29 11:28 UTC, sdelamo requested changes
@graemerocher could you fix the failing tests https://ge.micronaut.io/s/47lxjrr56ikgu/tests/overview?outcome=failed

2022-07-29 11:31 UTC, graemerocher commented
yes looking

2022-08-01 09:27 UTC, sdelamo approved these changes

2022-08-01 09:27 UTC, merged