feature: Allow stopping netty without stopping the application context
micronaut-projects/micronaut-core pull request #7933
Opened 2022-09-01 15:50 UTC by timyates

For CRaC, we need to be able to stop the Netty server when a checkpoint is made, but keep the ApplicationContext alive.

This change adds a new method to NettyEmbeddedServer to allow this.

2022-09-01 16:21 UTC, yawkat approved these changes

2022-09-01 16:22 UTC, yawkat commented
can you add a test

2022-09-01 16:22 UTC, timyates commented
There's an argument that this should go into 3.6.x, as otherwise I'll need to build the CRaC module against a snapshot of 3.7.0

2022-09-01 16:27 UTC, timyates commented
> can you add a test

@yawkat added here https://github.com/micronaut-projects/micronaut-core/pull/7933/commits/28dcb4270b5bed2e85ad64c9ebde54debc772290

2022-09-02 16:27 UTC, sdelamo requested changes

2022-09-02 16:27 UTC, sdelamo commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyEmbeddedServer.java
> +    NettyEmbeddedServer stopServerOnly();
Ad `@NonNull` to return type.

2022-09-02 16:27 UTC, sdelamo commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
> +    public NettyEmbeddedServer stopServerOnly() {
Ad `@NonNull` to return type.

2022-09-02 16:27 UTC, sdelamo commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
> +    private NettyEmbeddedServer stop(boolean stopApplicationContext) {
Ad `@NonNull` to return type.

2022-09-06 06:47 UTC, sdelamo approved these changes

2022-09-07 17:56 UTC, sdelamo commented
@dstepanov  @graemerocher any issues with this PR?

2022-09-12 09:28 UTC, graemerocher approved these changes

2022-09-12 09:39 UTC, merged