add an option to completely disable default property source loading
micronaut-projects/micronaut-core pull request #8016
Opened 2022-09-16 14:04 UTC by graemerocher

2022-09-16 15:45 UTC, dstepanov commented
I think the alternative to this should be setting `overrideConfigLocations` to nothing and disabling system and env property sources.

2022-09-16 16:04 UTC, sdelamo requested changes
Can you add documentation?

2022-09-16 16:04 UTC, sdelamo commented on inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
> +    public ApplicationContextBuilder enableDefaultPropertySources(boolean areEnabled) {
```suggestion
    @NonNull 
    public ApplicationContextBuilder enableDefaultPropertySources(boolean areEnabled) {
```

2022-09-16 16:06 UTC, sdelamo commented
What is the goal of this PR? Faster startup times when you don't want to lose time reading property sources on start-up? Should we add a member to the `@MicronautTest`annotation ? `@MicronautTest(enableDefaultPropertySources = false)`

2022-09-16 17:13 UTC, graemerocher commented
It isn't about startup time. Some teams do not want to load configuration from any other location other than the ones they specify manually via `builder.propertySources(..)` for security reasons. In addition for Micronaut for Spring and the starter we don't actually need Micronaut to load the property sources because these are already loaded by Spring so I think it will be valuable for that integration as well

2022-09-16 17:13 UTC, graemerocher commented
> Can you add documentation?

The documentation is the javadoc? Don't think this needs specific documentation in the user guide.

2022-09-16 17:21 UTC, graemerocher commented
On second though, I think docs explaining the behaviour would be good so I added some

2022-09-16 17:22 UTC, graemerocher commented
> I think the alternative to this should be setting `overrideConfigLocations` to nothing and disabling system and env property sources.

Think that is more work than needed, this adds a simply way to achieve that

2022-09-16 17:23 UTC, graemerocher commented
> What is the goal of this PR? Faster startup times when you don't want to lose time reading property sources on start-up? Should we add a member to the `@MicronautTest`annotation ? `@MicronautTest(enableDefaultPropertySources = false)`

we could but that will require a downstream change in MicronautTest that would need to be done at a later date, but like I said the goal is not faster startup.

2022-09-18 05:49 UTC, sdelamo approved these changes

2022-09-18 05:50 UTC, sdelamo commented
@dstepanov do you have any concerns merging this?

2022-09-18 06:20 UTC, dstepanov approved these changes

2022-09-19 05:07 UTC, merged