Fix wrong declairingType in groovy properties when get genericReturnType.
micronaut-projects/micronaut-core pull request #8084
Opened 2022-09-25 13:54 UTC by altro3

Fix wrong declairingType in groovy properties when get genericReturnType.

See https://github.com/micronaut-projects/micronaut-openapi/issues/670

2022-09-26 07:14 UTC, dstepanov requested changes

2022-09-26 07:14 UTC, dstepanov commented on inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
> -                        this,
Please keep the changes as before and introduce the same code as in `GroovyMethodElement` to  `GroovyPropertyElement`.

2022-09-26 07:20 UTC, dstepanov requested changes

2022-09-26 07:20 UTC, dstepanov commented on inject-groovy/src/test/groovy/io/micronaut/inject/visitor/ClassElementSpec.groovy
> +                if (memberEl.getDeclaringType().getType().getName() == type.getName()) {
Please also test that owner element is the correct one

2022-09-26 07:20 UTC, dstepanov commented on inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
>                  GroovyPropertyElement groovyPropertyElement = new GroovyPropertyElement(
FYI most of the code in elements contains `declaredType` but that's actually owned type. I'm working on a PR that changes it.

2022-09-26 08:49 UTC, altro3 commented
@dstepanov done

2022-09-26 10:02 UTC, dstepanov approved these changes

2022-09-28 05:01 UTC, sdelamo approved these changes

2022-09-28 05:02 UTC, merged