Remove the session module, and add micronaut-session
micronaut-projects/micronaut-core pull request #8281
Opened 2022-11-03 16:15 UTC by timyates

2022-11-03 17:55 UTC, timyates commented
Can you point me to the Upgrade wiki/doc?  As this will mean anything that is using a session will need the dependency changing

2022-11-26 20:21 UTC, timyates commented
@graemerocher Do we want to keep `session` here with an `api` dependency on `micronaut-session`?  That's what was done with `runtime`...however the session module is outside of micronaut-core so I'm not sure if that's something we want to do?

2022-11-27 13:28 UTC, sdelamo requested changes
You have to document this breaking change in https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/src/main/docs/guide/appendix/breaks.adoc

2022-11-27 13:28 UTC, sdelamo commented on src/main/docs/guide/httpServer/sessions.adoc
> +Rather than explicitly injecting the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] into a controller method, you can instead use https
define `https://micronaut-projects.github.io/micronaut-session/snapshot/api` in https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/gradle.properties and uses it in the asciidoc.

2022-11-27 13:28 UTC, sdelamo commented
> Can you point me to the Upgrade wiki/doc? As this will mean anything that is using a session will need the dependency changing

breaking changes are documented always in `breaks.adoc`

2022-11-27 15:14 UTC, timyates commented
Done and added to `breaks.adoc`

Fixed a couple of incorrect dependency macro usages there as well

2022-11-28 07:58 UTC, sdelamo approved these changes

2022-11-29 15:49 UTC, graemerocher approved these changes

2022-12-09 08:54 UTC, sdelamo approved these changes

2022-12-09 08:54 UTC, merged