Refactor and cleanup bean context
micronaut-projects/micronaut-core pull request #8479
Opened 2022-12-13 06:13 UTC by dstepanov

- Refactored `AbstractInitializableBeanDefinition` to have precalculated fields excluded  for better maintainability
- Removed old bean definition abstract classes
- Introduced `ObjectUtils.hash` as an alternative to `Objects.hash`, which doesn't allocate arrays (WDYT @melix ?).
- Removed unused info about reflection being required for the inject points

2022-12-13 11:52 UTC, graemerocher commented
tests broken

2022-12-16 17:56 UTC, graemerocher commented
still failing

2022-12-19 13:22 UTC, dstepanov commented
Passing now

2022-12-19 16:32 UTC, graemerocher requested changes

2022-12-19 16:32 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/InjectableBeanDefinition.java
> +public interface InjectableBeanDefinition<T> extends BeanDefinition<T> {
annotate internal IMO

2022-12-19 16:32 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/InstantiatableBeanDefinition.java
> +public interface InstantiatableBeanDefinition<T> extends BeanDefinition<T> {
annotate internal IMO

2022-12-19 16:32 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/InstantiatableBeanDefinition.java
> +    default T instantiate(BeanContext context) throws BeanInstantiationException {
nullability annotations

2022-12-19 16:32 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/InstantiatableBeanDefinition.java
> +    T instantiate(BeanResolutionContext resolutionContext, BeanContext context) throws BeanInstantiationException;
nullability annotations

2022-12-19 16:32 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/InstantiatableBeanDefinition.java
> +        return instantiate(new DefaultBeanResolutionContext(context, this), context);
should be wrapped in try with resources to that inject scoped beans are destroyed

2022-12-19 16:32 UTC, graemerocher commented on inject/src/main/java/io/micronaut/inject/ParametrizedInstantiatableBeanDefinition.java
> +public interface ParametrizedInstantiatableBeanDefinition<T> extends InstantiatableBeanDefinition<T> {
nullability annotations

2022-12-19 18:03 UTC, graemerocher approved these changes

2022-12-19 18:03 UTC, merged