Move to Geb 7 for Groovy 4 support
micronaut-projects/micronaut-core pull request #8575
Opened 2023-01-04 18:19 UTC by timyates

This removes test-suite-geb and puts the tests back in test-suite now we have a Geb that works with Groovy 4

Fixes #8569

2023-01-05 10:08 UTC, sdelamo requested changes
I think it is best to have all these tests in their own module.

2023-01-05 11:59 UTC, timyates commented
@sdelamo done 👍

2023-01-05 15:45 UTC, sdelamo approved these changes

2023-01-08 20:19 UTC, sdelamo commented
ping @melix

2023-01-09 07:30 UTC, melix approved these changes

2023-01-09 09:31 UTC, merged