Issue 8620 - deprecate ConversionService.SHARED
micronaut-projects/micronaut-core pull request #8644
Opened 2023-01-20 15:13 UTC by wetted

closes #8620

2023-01-20 16:19 UTC, alvarosanchez requested changes
Don't we have other references in core (tests, samples, docs, etc) that use still SHARED?

2023-01-20 16:19 UTC, alvarosanchez commented on core/src/main/java/io/micronaut/core/convert/ConversionService.java
> +     * @deprecated This will be removed in the next version. Use an injected {@link ConversionService} instead.
```suggestion
     * @deprecated This will be removed in the next major version. Use an injected {@link ConversionService} instead.
```

2023-01-20 16:23 UTC, wetted commented
> Don't we have other references in core (tests, samples, docs, etc) that use still SHARED?

Is that the scope of deprecating it in this Issue/PR (not disputing, just need to understand)?

2023-01-20 19:06 UTC, wetted commented
@sdelamo  @alvarosanchez There are 111 uses of `ConversionService.SHARED` in the 3.9.x branch. 98 in java files, 10 in groovy files, 3 in kotlin files and none -in adoc files.

Nine of them are for the docs examples under `test-suite[groovy|kotlin] and addressed in #8582

2023-01-23 08:10 UTC, alvarosanchez commented
I personally think that we should not use deprecated code ourselves, even in 3.9. And having references in documentation is even more concerning

2023-01-31 23:06 UTC, wetted commented
This superseded by #8695

2023-01-31 23:06 UTC, closed without merging