Remove docs for HTTP sessions and provide link to `micronaut-session` docs
micronaut-projects/micronaut-core pull request #8737
Opened 2023-02-07 21:23 UTC by wetted

closes #8735

2023-03-03 18:54 UTC, wetted commented
ping @sdelamo this is good to go. I don't know why CI still requires buiuld(8) and build(11). Those are bogus.

2023-03-05 15:18 UTC, sdelamo requested changes

2023-03-05 15:18 UTC, sdelamo commented on src/main/docs/guide/httpServer/sessions.adoc
> +See the documentation for link:https://micronaut-projects.github.io/micronaut-session/snapshot/guide/[Micronaut Session] for information about supporting HTTP sessions in your applications.
the url should be defined in `gradle.properties`

2023-03-05 15:24 UTC, sdelamo commented on src/main/docs/guide/httpServer/sessions.adoc
> +See the documentation for link:https://micronaut-projects.github.io/micronaut-session/snapshot/guide/[Micronaut Session] for information about supporting HTTP sessions in your applications.
Done via https://github.com/micronaut-projects/micronaut-core/pull/8737/commits/fb1a89dd26cce7acc4ab4622fae2a432daeaa431

2023-03-05 15:25 UTC, merged