build: Netty 4.1.89.Final
micronaut-projects/micronaut-core pull request #8774
Opened 2023-02-14 10:20 UTC by sdelamo

Closes#8773

Releases:

[Netty 4.1.89](https://netty.io/news/2023/02/13/4-1-89-Final.html) [Netty 4.1.88](https://netty.io/news/2023/02/12/4-1-88-Final.html) [Netty 4.1.87](https://netty.io/news/2023/01/12/4-1-87-Final.html)

Update versions in docs to be 2.0.58 instead of 2.0.58 for netty-tcnative-boringssl-static

2023-02-14 10:20 UTC, sdelamo commented
@yawkat not sure if we should merge this into 3.8.x or into 3.9.x

2023-02-14 10:49 UTC, graemerocher commented
3.8.x

2023-02-14 16:14 UTC, sdelamo commented on http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/NettyCorsSpec.groovy
> -        headerNames.contains("connection")
`contains` does not work in this `Set<String>`. It looks like a bug in netty.

2023-02-14 16:18 UTC, yawkat requested changes
pending https://github.com/netty/netty/pull/13219

2023-02-15 16:01 UTC, sdelamo commented
Upgrading to [Netty 4.1.87](https://netty.io/news/2023/01/12/4-1-87-Final.html) which does not have the regression. 88 has a different issue and 89 has https://github.com/netty/netty/pull/13219

2023-02-15 16:22 UTC, yawkat approved these changes

2023-02-15 16:58 UTC, merged