Adding test for headers to verify conformance to HTTP/1.1 4.2 Message Headers specification
micronaut-projects/micronaut-core pull request #8806
Opened 2023-02-20 20:11 UTC by wetted

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

closes #8687

2023-02-20 20:12 UTC, wetted commented
@yawkat what do you think? Should we trim leading/trailing whitespace and collapse LWS tp single SP for header values, as the spec suggests can happen?

2023-02-21 08:08 UTC, yawkat commented
Yes it should be accepted, and it already should work for netty. The test probably fails because the client doesn't allow it and that's fine.

2023-02-22 04:17 UTC, sdelamo requested changes
could you add to the test a custom header ?

`HttpRequest.GET("/bar/ok").header("fOO",  "ok")...`


` String getOkAsJson() {`


` String getOkAsJson(@Header("Foo") String bar) {`

2023-02-23 05:50 UTC, sdelamo approved these changes

2023-02-23 05:51 UTC, merged