Logback configuration defined via JAVA_TOOL_OPTIONS is ignored
micronaut-projects/micronaut-core pull request #9009
Opened 2023-03-27 14:16 UTC by timyates

Fixes #8596 

Previously, we only checked the classpath for logback configuration files, and when refreshing we ignored the `logback.configurationFile` setting.

This PR checks the filesystem if the config cannot be found on the classpath

It also adds `logback.configurationFile` as an optional property that points to the location of the config for when we refresh the configuration.

`logback.configurationFile` has precedence over the existing `logger.config` property

2023-03-27 15:44 UTC, sdelamo requested changes

2023-03-27 15:44 UTC, sdelamo commented on runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
> +        @Property(name = "logger.config") Optional<String> logbackXmlLocation
instead of using a `Optional<String>` use a `@Nullable String`

2023-03-27 15:49 UTC, timyates commented on runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
> +        @Property(name = "logger.config") Optional<String> logbackXmlLocation
And change

```
        this.logbackXmlLocation = logbackExternalConfigLocation.orElseGet(() -> logbackXmlLocation.orElse(DEFAULT_LOGBACK_LOCATION));
```

to be a load of `if`s?

2023-03-27 16:28 UTC, graemerocher approved these changes

2023-03-28 08:41 UTC, sdelamo commented on runtime/src/main/java/io/micronaut/logging/impl/LogbackLoggingSystem.java
> +        @Property(name = "logger.config") Optional<String> logbackXmlLocation
Yes.

2023-03-28 09:19 UTC, sdelamo approved these changes

2023-03-28 10:40 UTC, merged