Remove managed logging from catalog
micronaut-projects/micronaut-core pull request #9010
Opened 2023-03-27 15:01 UTC by timyates

We have micronaut-logging which publishes a BOM containing the managed logging libraries we want to use.

This PR stops exporting logger versions as managed dependencies.

This is a breaking change upstream, as any modules using mn.logback.classic will now need to change to importing micronaut-logging, and then using mnLogging.logback.classic

2023-03-28 10:38 UTC, sdelamo requested changes
I think what we should do is keep a version of logback in this repository to be used in the test classpath but micronaut-core should not depend on micronaut logging to avoid any cycles. 

logback related code in the main classpath should be moved to micronaut-logging

2023-03-29 12:54 UTC, timyates commented
@sdelamo @graemerocher @alvarosanchez @melix 

So there are some questions here.

1. Should we be moving certain (as yet undecided) logging code into micronaut-logging?
    - micronaut-logging is currently just a pom/catalog with the versions of logging we are using
2. micronaut-logging should now be added as a dependency by the Gradle and Maven build tools?
3. Are we ok keeping a version of logback in core (local to core) as suggested by Sergio?  Currently, there is no dependency cycle, as micronaut-logging is just a BOM, but if we move code in 1, I guess we should break the cycle here...

2023-03-29 13:04 UTC, graemerocher commented
1. To me it seems that we should move anything related to logback that exists in core to this module but perhaps it needs discussion
2. would have to be added explicitly by users I imagine
3. thing this would be fine

2023-03-30 08:35 UTC, timyates commented
@melix for when you get back, I guess we could we add mnLogging as a default import to micronaut-build?  Then we can switch mn.logback.classic to mnLogging.logback.classic in all our other modules

2023-04-03 08:45 UTC, melix commented
> I guess we could we add mnLogging as a default import to micronaut-build?

We can do this, yes

> Then we can switch mn.logback.classic to mnLogging.logback.classic in all our other modules

You can, already, right? By importing the catalog manually as any other micronaut catalog?

2023-05-10 09:51 UTC, graemerocher commented
Duplicate

2023-05-10 09:51 UTC, closed without merging