Fix broken link to checkstyle issue img
micronaut-projects/micronaut-core pull request #9047
Opened 2023-04-02 21:07 UTC by Januson

- Replaced broken link to checkstyle-issue.png with permalink

Note: Link is broken for all other repos as well.

2023-04-02 21:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=9047) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-core?pullRequest=9047) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-core?pullRequest=9047) it.</sub>

2023-04-03 14:53 UTC, sdelamo requested changes
Thanks, could you use `https://docs.micronaut.io/docsassets/img/checkstyle-issue.png` instead?

2023-04-03 18:49 UTC, Januson commented
@sdelamo Sure. Done.

2023-04-04 08:08 UTC, sdelamo approved these changes

2023-04-05 12:47 UTC, merged