Disable leak detection by default
micronaut-projects/micronaut-core pull request #9074
Opened 2023-04-06 14:17 UTC by yawkat

2023-04-06 15:24 UTC, dstepanov approved these changes

2023-04-06 18:12 UTC, graemerocher approved these changes

2023-04-10 09:26 UTC, sdelamo requested changes
@yawkat can you update the docs to clearly state that it is disabled by default and how to enable it. 

Currently,  it says: 

> Netty enables simplistic sampling resource leak detection which reports there is a leak or not, at the cost of small overhead. You can disable it or enable more advanced detection by setting property netty.resource-leak-detector-level to one of: SIMPLE (default), DISABLED, PARANOID or ADVANCED.

2023-04-11 06:37 UTC, yawkat commented
@sdelamo done

2023-04-11 08:23 UTC, merged