Fix ControllerConstraintHandlerTest for JDK client
micronaut-projects/micronaut-core pull request #9299
Opened 2023-05-22 15:52 UTC by timyates

2023-06-15 14:01 UTC, timyates commented
The TCK exclusions will be fixed in another PR (incoming as soon as I work out the issue) 😉

2023-06-21 10:07 UTC, sdelamo requested changes
Tim can you merge master against this PR and update the HTTP Client documentation to reflect the things which are not supported. 

Currently we say: 

```
[Proxy request](https://docs.micronaut.io/4.0.0-M3/guide/#proxyClient) support (we do support [HTTP Proxies](https://docs.micronaut.io/4.0.0-M3/guide/#proxy)).

Client Filters.

Streaming support.

Multipart requests.

H2C and HTTP/3.
```

Are any of those supported?

2023-06-21 10:17 UTC, timyates commented
> Are any of those supported?

I don't believe so

2023-06-22 15:45 UTC, sdelamo approved these changes

2023-06-22 15:46 UTC, merged