Add new base class for CertificateProvidedSslBuilder, SelfSignedSslBuilder and ACME
micronaut-projects/micronaut-core pull request #9369
Opened 2023-06-01 08:22 UTC by yawkat

The new class has a better API for replacing the key/trust stores without reimplementing the whole context builder setup. This will improve ACME compatibility.

2023-06-01 08:49 UTC, sdelamo commented
@yawkat please add prs to Github Projects.

2023-06-01 09:38 UTC, graemerocher requested changes

2023-06-01 09:38 UTC, graemerocher commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/AbstractServerSslBuilder.java
> +    public AbstractServerSslBuilder(ResourceResolver resourceResolver, HttpServerConfiguration httpServerConfiguration) {
javadoc constructor

2023-06-01 09:38 UTC, graemerocher commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/AbstractServerSslBuilder.java
> +    protected void processBuilder(SslContextBuilder sslBuilder, SslConfiguration ssl, HttpVersion httpVersion) {
add a comment in the body that the default implementation is a no-op

2023-06-01 09:38 UTC, graemerocher commented on http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/AbstractServerSslBuilder.java
> +    protected void processBuilder(SslContextBuilder sslBuilder, SslConfiguration ssl, HttpVersion httpVersion) {
add nullability annotations to the arguments

2023-06-02 16:30 UTC, graemerocher approved these changes

2023-06-04 19:01 UTC, merged