Method binding with no @Body TCK tests, updated docs and docs examples.
micronaut-projects/micronaut-core pull request #9479
Opened 2023-06-21 20:18 UTC by wetted

Add http-tck tests for json and form data body and controller with no `@Body` annotation.
Update binding docs, and add docs examples for java, groovy, kotlin.

closes #9388

2023-06-22 06:03 UTC, sdelamo requested changes
Can you use [Kotlin Data Classes](https://kotlinlang.org/docs/data-classes.html) for the `Point` class in Kotlin ?

2023-06-22 07:05 UTC, yawkat approved these changes

2023-06-22 15:40 UTC, sdelamo requested changes

2023-06-22 15:40 UTC, sdelamo commented on test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/binding/PointController.kt
> +    fun noBodyJson(x: Int, y: Int): Point { // (1)
I think you could change:

```
 fun noBodyJson(x: Int, y: Int): Point { // (1)
        return Point(x, y)
    }
```

to

```
 fun noBodyJson(x: Int, y: Int) = Point(x,y)
```

which is more Kotlin idiomatic.

2023-06-22 15:40 UTC, sdelamo commented on test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/binding/PointController.kt
> +    fun noBodyJson(x: Int, y: Int): Point { // (1)
same in the other method and in the other controller

2023-06-22 16:19 UTC, wetted commented on test-suite-kotlin-ksp/src/test/kotlin/io/micronaut/docs/server/binding/PointController.kt
> +    fun noBodyJson(x: Int, y: Int): Point { // (1)
Cool. Thanks for the suggestion. I should probably spend some more time in the Kotlin Primer. :)

2023-06-23 12:29 UTC, sdelamo approved these changes

2023-06-23 12:29 UTC, merged