Core Test java 21
micronaut-projects/micronaut-core pull request #9985
Opened 2023-10-16 11:33 UTC by dstepanov

2023-10-16 11:51 UTC, dstepanov commented
Looks like 21 build took all the tasks from cache...

2023-10-17 10:39 UTC, timyates commented
It took them from the cached java 17 ones

https://ge.micronaut.io/s/xnwym4gcburfo/timeline?details=uvi2dadwsnupq&page=2

That doesn't seem right...

@melix Java version change should invalidate the cache shouldn't it?

2023-10-17 10:39 UTC, timyates commented
@dstepanov I think you also need to set the jvm version to 17 (or something less than 21) for kotlin compilation

2023-10-17 10:41 UTC, dstepanov commented
How?

2023-10-17 10:45 UTC, timyates commented
I cannot currently see why this works without having to do something like https://github.com/micronaut-projects/micronaut-crac/blob/master/test-suite-kotlin-ksp/build.gradle.kts#L18-L25

2023-10-17 10:51 UTC, timyates commented
Ahhh, we already set jvmTarget to 17 it seems in multiple places...

2023-10-17 10:59 UTC, timyates commented
All tasks in this PR and https://github.com/micronaut-projects/micronaut-core/pull/9978 are being run through Java 17 via the Gradle toolchain support 😞

2023-10-17 11:40 UTC, timyates commented
@dstepanov [pushed a change to actually use the JDK version](https://github.com/micronaut-projects/micronaut-core/pull/9985/commits/bd55a2b30c613f6ff09ff07d6e8c4417cd60c5d6) that gradle is being executed by

I think `:context-propagation:kaptKotlin` is failing

2023-10-17 12:08 UTC, melix requested changes

2023-10-17 12:08 UTC, melix commented on core-reactive/build.gradle
> +tasks.named("compileTestKotlin") {
This should be done in a common plugin rather than copy/pasting into every build script

2023-10-17 12:10 UTC, melix commented
> All tasks in this PR and https://github.com/micronaut-projects/micronaut-core/pull/9978 are being run through Java 17 via the Gradle toolchain support 😞

We should really not mix the VM used to run the build with the one used to build/run the tests. That's because ideally we shouldn't have to rebuild everything _just_ to test that it works on 21: there should be 2 tasks which test different JDK versions. Since we're not there and that it would require many changes to our scripts, then it means that you have to update the test tasks to use the toolchain which matches the VM that the build is running on.

2023-10-17 12:12 UTC, timyates commented
> it means that you have to update the test tasks to use the toolchain which matches the VM that the build is running on.

Do you have a link showing how this is done?

2023-10-17 12:12 UTC, melix commented on buildSrc/src/main/groovy/io.micronaut.build.internal.convention-base.gradle
> +    javaVersion = JavaVersion.current().majorVersion.toInteger()
To be clear, this is a risky change. As potentially, this means that we could have a release workflow which accidentally uses Java 21 and release a version with the wrong version.

The build should compile on 17, not 21. What you want is running _tests_ on 21, I think.

2023-10-17 16:35 UTC, timyates commented
@dstepanov can we close this as superseded by https://github.com/micronaut-projects/micronaut-core/pull/9989 ?

Thanks for all the help 👍

2023-10-17 17:17 UTC, closed without merging